### ISSUE TITLE
[feature] language packs

### ISSUE THREAD

**Issue by juzman** [indywidualny/FaceSlim#100]
Have been looking at all the new commits, cannot wait for a new build. :+1: 

A query I had (I guess I could pull and modify / compile myself) would be create an "English only" version (thus being even slimmer), then have option to "add language" and have separate language packs?

Is that kind of thing even possible?

Woo, up to #100!

**Comment by indywidualny** [comment]
Well. All the extra translations takes about 60 KB of total space.

It's probably possible but... IMHO it's really not necessary to save a few kilobytes.

My goal is keep app size below 1 MB. It's really small. I'm adding an crash report sender and changing a notification service so the size of the next release will be bigger than now. But still below 1 MB. 

Although if your want it slimmer just delete all the values-XX directories (except for values-v21, values-v19, values). It will remove all the translations in your build and the app will be English only.

**Comment by juzman** [comment]
Thanks for the information. :-)
