### ISSUE TITLE
[Feature request] Add an option to hide people you may know

### ISSUE THREAD

**Issue by juzman** [indywidualny/FaceSlim#101]
I love the option to "hide sponsored posts". Is it possible to hide "people you may know" too?

**Comment by indywidualny** [comment]
Yep. Please just help me to locate the right element at m.facebook.com.
I will add a rule to hide it.

sob., 9.01.2016, 06:03 Justyn Smith użytkownik <notifications@github.com>
napisał:

**Comment by juzman** [comment]
The section on m.facebook.com is the article bit I am guessing?

<article class="_55wo _5rgr _5gh8 _35au" data-sigil="story-div"><header class="_5yxt _5qc1 _177o"><h3 class="_52jd _52jb _52jh _5qc3 _24u1 _5x3- _2l5u">People You May Know</h3>
.....
</article>

**Comment by indywidualny** [comment]
I mean HTML div ;)

**Comment by juzman** [comment]
Whoops, it isn't in a div.

`<article class="_55wo _5rgr _5gh8 _35au" data-sigil="story-div"><header class="_5yxt _5qc1 _177o"><h3 class="_52jd _52jb _52jh _5qc3 _24u1 _5x3- _2l5u">People You May Know</h3>.....</article>`

**Comment by indywidualny** [comment]
Thanks! Should I add this option separately or combine it with Hide
Newsfeed, like it was planned?

sob., 9.01.2016, 23:16 Justyn Smith użytkownik <notifications@github.com>
napisał:

**Comment by juzman** [comment]
Catch22? I would add it separately just in case people only want to hide
one or the other. :-)

**Comment by indywidualny** [comment]
It may not always work. Opened for now. Will be marked as beta.

**Comment by juzman** [comment]
Is there any examples of it not working? I'm sure I got the right CSS / HTML code for the People You May Know div.

**Comment by indywidualny** [comment]
I remember seeing it once even if the option was activated. Perhaps everything is alright and I'm mistaken. It need to be tested but any changes will be added later. For now I'm just going to release this version.

**Comment by juzman** [comment]
I know you initially see "people you may know" when the news feed first
loads, then it disappears. Happens on mine.

**Comment by indywidualny** [comment]
Ok, great. So it works.
