### ISSUE TITLE
2.2.0 soon

### ISSUE THREAD

**Issue by indywidualny** [indywidualny/FaceSlim#106]
New release soon. Perhaps tomorrow if everything is alright. Hide sponsored posts/ads AND hide people you may know, may not be perfect now, so I'm going to mention these options are in beta.

If someone is going to pull something, please be quick :)
Thanks for your help, 58 commits since the last release, a lot of things have been changed and I like it.

**Comment by pejakm** [comment]
Don't make the new release yet, please. Image downloading is not working after latest changes, I'm trying to figure out why.

**Comment by indywidualny** [comment]
Oh. Something with permissions. I know what's wrong and I will fix it.

sob., 16.01.2016, 12:45 Mladen Pejaković użytkownik <
notifications@github.com> napisał:

**Comment by indywidualny** [comment]
What about file upload? Is it OK?

sob., 16.01.2016, 12:48 koras użytkownik <koras@indywidualni.org> napisał:

**Comment by pejakm** [comment]
> What about file upload? Is it OK?

Uploading existing image on phone is okay. Uploading from camera is not working, but I actually never tried it before so I'm not sure whether it worked previously.

**Comment by pejakm** [comment]
Also, on line https://github.com/indywidualny/FaceSlim/commit/d6eb19bda283315755f434a2745faf122a667a48#diff-2029b684426bb97ea4fe89d3d69a5369R953 there's a "FaceSlim" leftover (should be `appDirectoryName`, right?)

**Comment by indywidualny** [comment]
https://github.com/indywidualny/FaceSlim/blob/master/app/src/main/java/org/indywidualni/fblite/activity/MainActivity.java#L119

appDirectoryName = getString(R.string.app_name).replace(" ", "");

To

appDirectoryName ="/" + getString(R.string.app_name).replace(" ", "");

Changes anything? 

"FaceSlim" leftover should be changed to appDirectoryName. 

I have no access to my PC to build it and check now.

**Comment by pejakm** [comment]
Nope, not working. A toast "Downloading image..." isn't displayed, also FaceSlim directory is not created. Which could mean that `saveImageToDisk` function isn't triggered at all.

**Comment by pejakm** [comment]
That was it, working fine now. :)
