### ISSUE TITLE
Missing send button in chat when 'disable images' option is enabled

### ISSUE THREAD

**Issue by uniqdom** [indywidualny/FaceSlim#114]
When you enable 'disable images' option, there is no send button in chat. The same thing goes for the 'thumb up' button.

**Comment by indywidualny** [comment]
Is there any possibility to send a message? Clicking somewhere where this
button should be located for example?

czw., 21.01.2016, 23:13 uniqdom użytkownik <notifications@github.com>
napisał:

**Comment by pejakm** [comment]
> Is there any possibility to send a message? Clicking somewhere where this
button should be located for example?

Unfortunatelly, no.

**Comment by indywidualny** [comment]
Not good. But in order to fix it we need to locate this button in css and
show it. In a webview package there is a class in which all the elements
are being hidden somewhere.

pt., 22.01.2016, 00:21 Mladen Pejaković użytkownik <notifications@github.com>
napisał:

**Comment by mcastillof** [comment]
does this help? https://imgur.com/2G7jqRS
