### ISSUE TITLE
[Feature Request] Change Messages widget icon 

### ISSUE THREAD

**Issue by bnbrown** [indywidualny/FaceSlim#116]
First, love the app, and recommend it to everyone! Would it possible to change the shape of the messages widget icon to a word bubble style? I find myself tapping on messages all the time for the regular FB front page because the icons are both the same.

**Comment by indywidualny** [comment]
Could you generate a sample icon, please?
Just to show me what you are expecting - http://romannurik.github.io/AndroidAssetStudio/icons-launcher.html#foreground.space.trim=1&foreground.space.pad=0&foreColor=607d8b%2C0&crop=0&backgroundShape=square&backColor=ffffff%2C100&effects=none

**Comment by bnbrown** [comment]
This is a transparent png, and doesn't show well on this white background. I will try and use the editor you posted for a more easily view-able example?

![faceslimbubble](https://cloud.githubusercontent.com/assets/16924450/12625020/7f68e64c-c4f7-11e5-8f86-8a3e8b571ff8.png)

**Comment by bnbrown** [comment]
With a filled background from the generator:
![download](https://cloud.githubusercontent.com/assets/16924450/12625245/8dbf9d98-c4f8-11e5-990f-ab540f8df59b.png)

**Comment by indywidualny** [comment]
Can it be something simple? http://romannurik.github.io/AndroidAssetStudio/icons-launcher.html#foreground.type=clipart&foreground.space.trim=1&foreground.space.pad=0.2&foreground.clipart=res%2Fclipart%2Ficons%2Fcommunication_chat.svg&foreColor=3b5998%2C0&crop=0&backgroundShape=square&backColor=ffffff%2C100&effects=shadow

I suck at image editing. It has to be generated :D

**Comment by bnbrown** [comment]
How about this? 

![roundfs](https://cloud.githubusercontent.com/assets/16924450/12689251/47a6cdfe-c6a1-11e5-8bed-0cf7a48c0c2c.png)

**Comment by indywidualny** [comment]
Awesome. Thanks. I will add this soon :)
