### ISSUE TITLE
LED on Marshmallow

### ISSUE THREAD

**Issue by creativetrendsapps** [indywidualny/FaceSlim#121]
For some reason the LED light doesn't work with Marshmallow devices namely Samsung devices with Marshmallow. Is there a way this can be fixed? LED is checked in the settings menu. Vibrate and ringtone work fine, just the LED doesn't turn on at all.

**Comment by indywidualny** [comment]
Strange thing. It's working on my Nexus with Marshmallow. I will investigate it. Is the option enabled? Try to disable it and enable again. Maybe something was not saved.

**Comment by creativetrendsapps** [comment]
Yes it's enabled in settings. It's only happening on Samsung devices with Marshmallow.

**Comment by indywidualny** [comment]
I have an idea. It's gonna be fixed soon (I hope).
