### ISSUE TITLE
[Suggestion] Twitter

### ISSUE THREAD

**Issue by bastadur** [indywidualny/FaceSlim#128]
This may seem a bit radical and I'm not sure if you are going to consider it, but is there a chance of including a twitter wrapper too inside the app? I tried two apps that include both facebook and twitter and it's really convenient to have them together in an app.

**Comment by indywidualny** [comment]
The idea is nice however the app is strictly designed for Facebook. Major changes are required to introduce it. It's just too much for one person :D Ok, maybe not too much, but it would take a long time, it would cause new problems and the app would become too complicated to just be "slim". It's a huge change and it also seems quite pointless to me. I would like to create new things, learn some stuff. The main idea was to create a pretty nice Facebook wrapper and I achieved it. It was never my plan to combine it with Twitter wrapper.

There are great apps for Twitter. Maybe there is something for you.
https://play.google.com/store/apps/details?id=com.klinker.android.twitter_l
The best Twitter app I've ever used. It's just AWESOME

**Comment by G33KS44n** [comment]
I totally agree with Koras. This app is for Facebook purpose.

There are apps for Twitter. Twitter has their own Official App. They are
all available at the stores of different platforms.

Cheers!
 Sayantan

**Comment by kamathln** [comment]
Individualny: Yes. This app is specifically meant for Facebook. But as long as you are trying to "learn some stuff" , try to generalize your code (I haven't seen it though) as much as possible, in such a way that it can be adapted easily for wrapping other websites. 

Bastadur: Try learning from the code of this app, and try making your own _seperate_ "TwitSlim" .
