### ISSUE TITLE
Question about user agent

### ISSUE THREAD

**Issue by nwhr** [indywidualny/FaceSlim#129]
I find FaceSlim useful for privacy matters but I failed at trying to recognize which user agent it shows to facebook. I've tried to switch my default UA with several apps but they are programmed to spoof it only for chrome, I just want to hide my device information from UA string. Can you override it somehow to show some generic UA string without showing model and device id? Maybe googling "most common user agent" may help. Thank you.

**Comment by indywidualny** [comment]
Oh, it seems like a nice idea. Thanks, I will.

**Comment by G33KS44n** [comment]
Awesome

**Comment by indywidualny** [comment]
Done.
