### ISSUE TITLE
New "Like" buttons don't work when "Long click to share" is enabled

### ISSUE THREAD

**Issue by xavihernandez** [indywidualny/FaceSlim#133]
Hi,

Thanks for this app :)
According to last Facebook update you should try to make aceSlim compatible with new "Like" image buttons ("I adore", "Haha", "Wouah", "Sad", "Grrr").

**Comment by indywidualny** [comment]
It seems to be working fine. The only issue is invoking long click share as
well. I have to modify a click detector to ignore it.

śr., 24.02.2016, 16:08 Eric Mourougandy użytkownik <notifications@github.com>
napisał:

**Comment by xavihernandez** [comment]
@indywidualny Thanks for your answer.

How does it work?
On desktop you have to put your mouse icon above "Like" button, and the others popup.

**Comment by indywidualny** [comment]
Long click "like" please :)

śr., 24.02.2016, 16:37 Eric Mourougandy użytkownik <notifications@github.com>
napisał:

**Comment by xavihernandez** [comment]
Nothing happens

**Comment by xavihernandez** [comment]
I have latest verison 2.4.0

**Comment by xavihernandez** [comment]
@indywidualny ok I have reached to make it worj by disabling "long click to share", I hadn't understood why you told me that in your message, now I see :)

**Comment by indywidualny** [comment]
It even works with long clicks enabled. Just long-click a little shorter. This way long click will not be recognized by app listener but it will be recognized by Facebook :)
