### ISSUE TITLE
[Feature Request] always start in most recent mode

### ISSUE THREAD

**Issue by frauhottelmann** [indywidualny/FaceSlim#136]
First, let me thank you for creating this app!
Now to my request. In my desktop browser I always open FB in most recent mode (via https://www.facebook.com/?sk=h_chr). In the app it sometimes does that, when I open it and had in that mode before, but sometimes it defaults to "Top Stories". Could you make it an option to always start in in most recent mode?

**Comment by indywidualny** [comment]
Ok, it's easy to add. I will add it to the next release.

**Comment by frauhottelmann** [comment]
Awesome. Thanks. I'll try and update the German translations. There are a few missing strings.
