### ISSUE TITLE
App is stopped after long scrolling down

### ISSUE THREAD

**Issue by NeroBurner** [indywidualny/FaceSlim#139]
Sometimes the app stops with the message box with faceslim was stopped. The last time it happened when scrolling down through many messages without klicking links. Just scrolling through messages.

How can I debug this issue? Could it be, that the app is closed because all the messages and pictures are kept in ram and the device has to kill a process?

Thanks in advance

Device: Samsung Galaxy S4 Mini
Android: 4.4.2

**Comment by indywidualny** [comment]
That's exactly why it happened. To little RAM to keep all the necessary things and system couldn't manage to get more memory. Because you were scrolling there was no way to free some memory used by this app because you wouldn't be able to scroll it back. So it crashed.

**Comment by NeroBurner** [comment]
Instead of crashing by using ever more RAM could there be a local cache. Only x postings are kept in ram, the oldest postings are swapped out into the cache?

**Comment by indywidualny** [comment]
I'm afraid it's not possible because the WebView doesn't provide such a functionality. It's not a recyclerview. So it may happen but rarely. Nothing to do here.
