### ISSUE TITLE
Default news feed.

### ISSUE THREAD

**Issue by Techwolf** [indywidualny/FaceSlim#140]
The default page is usually the news feed. I like to be able to set it to either Top Stories or Most Recent, URL for most recent is https://www.facebook.com/?sk=h_chr Note that "news" is misleading, it not real news, but posts of "liked" pages/folks/etc. And I prefer then in chrono order due to seeing the same post again and again while recent posts are buried and is missed in "Top Stories" mode.

**Comment by indywidualny** [comment]
Hi. It's actually #136. I will do it in the next release. You will be able to choose a default "News" mode.
