### ISSUE TITLE
App update 

### ISSUE THREAD

**Issue by homersimpsons** [indywidualny/FaceSlim#142]
In settings it could have an option to download the latest version (If it's not the actual one). Because this app could provide a lot of interest and maybe some people would not have to install F-Droid only for this app.

**Comment by jidanni** [comment]
Yes PLEASE some popup with a button to update or something… anything other than that horrible terrible bulky F-droid monster that takes100 times longer to update than this one little app I need it for.

**Comment by indywidualny** [comment]
I will think about it. It's actually easy. Ok, but it requires a short
network connection every app start -  just to compare a current release
number.

niedz., 12.06.2016, 09:05 użytkownik Dan Jacobson <notifications@github.com>
napisał:

**Comment by indywidualny** [comment]
Done.
