### ISSUE TITLE
Metal for Facebook

### ISSUE THREAD

**Issue by drbeat** [indywidualny/FaceSlim#143]
So I started using Metal for Facebook since I reactivated my FB account.

I noticed something... the AMOLED Theme seemed familiar to me.

I think the Dev is using your black.css. I noticed some definitions I did for your black.css

Can you have a look on it and confirm?
They should credit you then if they are using it.

**Comment by indywidualny** [comment]
It's ok. If someone is using this style elsewhere, good for them :)
It would be nice of them to inform about it but I don't really care.

**Comment by drbeat** [comment]
Ok. I thought I should let you know ;)

btw have you thought about using jsoup to crawl the information and display it in material layout?

**Comment by indywidualny** [comment]
Not yet but I'm thinking of maybe rebuilding it completely in the future. To make it more "android", less webview frame.
