### ISSUE TITLE
Most Recent Not So Much 

### ISSUE THREAD

**Issue by ITGeekMonkeys** [indywidualny/FaceSlim#145]
Most Recent doesn’t always show the most recent story. Pulling down to refresh will show a post from 14 hours ago. Pull down again and it might show the most recent story as being posted 7 hours ago. I find the only way to assure that I see the most recent story or post is to go to through the menu.

**Comment by indywidualny** [comment]
Choosing the feed version from the menu should be remembered. Is it?

**Comment by Dostoi** [comment]
From which menu ?
The app one or the facebook one ? 
Because if it's facebook's, it always end up switching on it's one to the other mode (not most recent but most "interesesting to us" (according to facebook)) after some time

**Comment by indywidualny** [comment]
Facebook menu...

Ok. I will think about it how to make the change permanent.

pon., 13.06.2016, 14:33 użytkownik Dostoi <notifications@github.com>
napisał:

**Comment by Dostoi** [comment]
I was asking because I didn't know if there was an option in the app somewhere
Thanks :)
