### ISSUE TITLE
Feature Request - Location Services

### ISSUE THREAD

**Issue by bnbrown** [indywidualny/FaceSlim#151]
Still loving the app, and recommend it to everyone! One thing I would love to have is the ability to use location services for "check ins"
I couldn't figure out why it wouldn't find my location in a new post when I even tried using search until I realized that the app doesn't have location services permissions. 
Could you add location services permissions for the app? I'm sure everyone doesn't want that, but it would be great for me.
Perhaps an in app settings switch to turn location services on or off for those who want more privacy?
Again, thanks for all the hard work on the app!

**Comment by indywidualny** [comment]
Done.
