### ISSUE TITLE
Crash: messages tab

### ISSUE THREAD

**Issue by indywidualny** [indywidualny/FaceSlim#153]
I'm currently working on it.

**Comment by creativetrendsapps** [comment]
What is actually causing this crash?

**Comment by indywidualny** [comment]
They did something to make this link open their official messages app I suppose. A webview client tried to handle it as an external url and was sending an intent to view the link with a different app. Apparently me, you and some users doesn't have facebook messenger installed to open this specific Uri scheme so the right activity couldn't be found by the system and ActivityNotFoundException was thrown. Now I'm simply catching it to ignore the problem. If someone is using Facebook messenger it is supposed to be opened by clicking this tab.

**Comment by creativetrendsapps** [comment]
Oh, ok. So just tapping the messages tab causes this to happen? Facebook sucks.

**Comment by indywidualny** [comment]
Yep. Well, when someone is using their messaging app and the web version of the site it's quite useful. Their idea doesn't necessarily suck, it just need to be handled properly by a wrapper :) One line of code and this is fixed.
