### ISSUE TITLE
Using Face Slim with free Social MB gifted by the mobile companies

### ISSUE THREAD

**Issue by logos88** [indywidualny/FaceSlim#157]
Hi. I have a mobile companie which gives you free social MB to use with whatsapp and facebook. But it only works with the official facebook app, I can´t use Face Slim with this free mb. ¿Would be any way to use them with Face Slim?

The Promo is this one:
http://wom.cl/bases/bases/2016/redes-sociales/PLANES-COMPATIBLES-PROMO-PREPAGO-OK.pdf

**Comment by indywidualny** [comment]
Short answer. No, it's not possible. It's not the official Facebook app.

wt., 19.04.2016, 17:23 użytkownik logos <notifications@github.com> napisał:

**Comment by logos88** [comment]
Oks, I imagined. It´s a pity but I´ll stick with Face Slim anyway.
