### ISSUE TITLE
Would it be possible to hide posts like "person X liked/commented on person Y's status"?

### ISSUE THREAD

**Issue by Hund** [indywidualny/FaceSlim#158]
I have very few people on Facebook and I follow only a handful of them. 
Because of this Facebook is showing me a ridiculous amount of posts like "person X liked/commented on person Y's status". And person Y being some random  person I heard of.

Would it be possible to hide those posts? It's probably a long shot, but its worth asking at least.

**Comment by indywidualny** [comment]
Hi. I'm not planning to do it now but thanks for a suggestion. It seems to be a nice idea but it would require too many modifications and I suppose it's not even possible to modify Facebook mobile website so much. I could encounter a problem with a dynamically loaded content for sure. Just like hiding sponsored posts. It's not reliable although it works sometimes.

**Comment by Hund** [comment]
I see. Thank you! :)
