### ISSUE TITLE
[Feature Request] Context menu for pictures

### ISSUE THREAD

**Issue by de-live-gdev** [indywidualny/FaceSlim#16]
Would be great if the context menu would also be there when long-clicking on a single picture.
So the ability to share && / || save would be great to see!

Now it only works for albums, because thats a link.

**Comment by indywidualny** [comment]
Done. Saving an image for now. I will add "share" later. Works for full size images.

**Comment by de-live-gdev** [comment]
great, thanks :+1:

**Comment by Betacentury** [comment]
It would be great!
