### ISSUE TITLE
Notification drawer in black theme not readable

### ISSUE THREAD

**Issue by xavihernandez** [indywidualny/FaceSlim#161]
Hi, first thanks for this application of course.

I have noticed "Notifications" (World image button) are not easily readable when Black Theme is applied. New notifications appear as white text on white (clear at least) background :(. When they are read, they become white text on black background.

I think it has been introduced in v2.4.2

**Comment by indywidualny** [comment]
@drbeat, are you still interested in adding some changes to the black CSS? It looks like a small modification to introduce. I'm not using a black one so often and didn't modify it recently, so it would be great if you could look into it :)

**Comment by indywidualny** [comment]
Ok, so it's gonna be released at the end of this week.

**Comment by xavihernandez** [comment]
Great!
Big thanks :)

**Comment by kamathln** [comment]
Not much experience in Android or Java programming, but was thinking of a permanent solution:

1.  track the asset images from the original CSS. If we have new one, modify it automatically to match the black theme by applying filters (negative and grayscale) and store/cache it. 
1.  re-generate a black theme CSS by modifying the original Facebook CSS. 

Advantage: automatic correct CSS generation, no matter if new assets come in , or if some different locale chosen has a different CSS and assets, etc. 

Is it possible to implement this?

**Comment by indywidualny** [comment]
It's actually possible but quite complicated. And it wouldn't necessarily work as intended. There are a lot of resources in Facebook CSS. It's hard to determine which ones we need in grey scale. Some images which we need to keep unmodified could suffer.

It's fixed now so imho is easier to fix it sometimes than apply this permanent but complicated solution which should affect some images we would like to keep.

**Comment by kamathln** [comment]
Ah! Thanks for the explanation, I understand now. I had assumed all the images are filtered the same.
