### ISSUE TITLE
Broken layout on Amazon Fire 7" 2015 Tablet

### ISSUE THREAD

**Issue by juk47ht** [indywidualny/FaceSlim#166]
Hi. Just a small issue that I have with FaceSlim on my Amazon Fire 7" 2015 Tablet. I have installed a custom rom on my tablet and FaceSlim looks like the below image when browsing on any profile. The surname is half missing, the about tabs are overlap each other, etc. FaceSlim's layout has great on my phone by the way.

If this is a quick fix, I'd really appreciate it. If it is not, then forget it. It is certainly not a deal-breaker for such an awesome app that is FaceSlim. 

![screenshot_2016-05-18-22-13-42](https://cloud.githubusercontent.com/assets/7393887/15375555/9ef5705e-1d47-11e6-8d12-5571a831b5af.png)

**Comment by indywidualny** [comment]
To be honest I'm not sure what's wrong. That's why there is not rather a quick fix. It's something wrong with a webview itself I suppose.

**Comment by juk47ht** [comment]
The device is a low-end tablet so I think I should consider myself lucky to even open a webpage at all :)

**Comment by indywidualny** [comment]
Try to update this if you can https://play.google.com/store/apps/details?id=com.google.android.webview

**Comment by juk47ht** [comment]
I didn't have Android Webview installed on my tablet and after installing it, the problem was solved. Thank you!

**Comment by indywidualny** [comment]
It's a system app so you had it installed for sure. It was just outdated. Glad it works ;)
