### ISSUE TITLE
Messaging doesn't work anymore

### ISSUE THREAD

**Issue by sirmacik** [indywidualny/FaceSlim#169]
Don't know if Facebook closed something, but when you try to open messages app crashes. Probably yes, there was some kind of message from website but it didn't finished loading before crash.

To reproduce try to open „messages” via FaceSlim.

**Comment by indywidualny** [comment]
Which app version?

śr., 1.06.2016, 11:07 użytkownik sirmacik <notifications@github.com>
napisał:

**Comment by sirmacik** [comment]
2.4.2, after reading changelog it looks like I've missed few updates. F-droid isn't as good at it as I'd like it to be. Sorry for the buzz.

**Comment by indywidualny** [comment]
:)

śr., 1.06.2016, 11:19 użytkownik sirmacik <notifications@github.com>
napisał:
