### ISSUE TITLE
Chat page - Bad user experience and send bugs

### ISSUE THREAD

**Issue by gsantner** [indywidualny/FaceSlim#170]
Current webview representation of the facebook chat site (chat.facebook.com) is horrible.
Mostly sending messages with app on the chat site doesn't work.

Some examples:
* Enter/Send key duplicates last word of entered text, needs like 5 clicks on enter to send message
* Click on message entry box pop keyboard up, box not visible anymore
* Message content below navbar
* Message content very bad readability, too light
* Chat header (Name, last seen, ...) goes away

A first step would be to disable content inside navbar if ( page startswith chat.facebook.com), even if the SharedPrefence is set to show content below. Enabling content below navbar does maybe make sense for the normal facebook site (and the normal message system), but not for the chat.

Device: Nexus 5,  6.0.1,  App version 2.5.2

Here are some  unordered screenshots:

<img src="https://cloud.githubusercontent.com/assets/6735650/15757129/6e1c99bc-2904-11e6-8f12-c031fee36df9.png" width="30%" height="30%"> <img src="https://cloud.githubusercontent.com/assets/6735650/15757127/6dfecf40-2904-11e6-8a4d-57cedd4e592b.png" width="30%" height="30%"><img src="https://cloud.githubusercontent.com/assets/6735650/15757128/6dfff30c-2904-11e6-9b85-49a075180862.png" width="30%" height="30%"><img src="https://cloud.githubusercontent.com/assets/6735650/15757130/6e220276-2904-11e6-85f7-2d36c82e2b41.png" width="30%" height="30%">

If I have enough time I can maybe submit some commits.

**Comment by gsantner** [comment]
I tried setting public static final String MESSENGER_URL = " https://mbasic.facebook.com/messages"; in MainActivity.java, which works better a lot.
But I don't know if facebook will also redirect to messanger from there soon. 

Here is some (but no all) black.css for `mbasic.facebook.com/messages`
```
.b, .e, .bv, .bw, #u_0_0, .b .bf, .b a.bm, .b a.bm:visited, .b a.bh, .b a.bh:visited, .bg {
	background: #000000;
}

.b a.bh, .b a.bh:visited {
	font-weight: bold;
}
```

**Comment by indywidualny** [comment]
They will soon. The only reliable solution is online messenger url. I know it's buggy but at least it works.

**Comment by indywidualny** [comment]
Ok. Please use standard chat because it's avaliable again now. I left mobile messenger for people who like it. It's still at the drawer menu.
