### ISSUE TITLE
facebook imposing messager 

### ISSUE THREAD

**Issue by abate** [indywidualny/FaceSlim#171]
Facebook is slowly imposing messager to everybody. Is there a way to get back the old interface (faster, cleaner and more responsive) ? I can still get to it by going to the news feed, clicking on the messages icon, and the closing the annoying window asking me to install messanger. The interface I get when I select messages from the side menu does not really work. It is sluggish and while I write a message it often gets jumbled up  . Is faceslim doomed to succumb to facebook decision to change the messaging interface ?

**Comment by indywidualny** [comment]
Let's say every wrapper-like app for Facebook is gonna suffer from this. There is nothing to do to prevent them from removing old messages. We rely on mobile website so if they disable something it's also disabled for us. It sucks but there is nothing to do.

I don't use Facebook so much personally so it's not a problem for me but it sucks indeed.

**Comment by palfrey** [comment]
Fixed by #155 I think

**Comment by indywidualny** [comment]
Yep.
