### ISSUE TITLE
Application on Play Store

### ISSUE THREAD

**Issue by axtux** [indywidualny/FaceSlim#172]
Hello,

I just installed your app and find it very useful, mostly for messenger and messenger notifications. When I like ideas, I also like to spread them. Most people don't know how to install applications that are not on Google Play. I would suggest you to publish your app for those people to be able to use it.

I saw on [Face Slim Donation on Play Store](https://play.google.com/store/apps/details?id=org.indywidualni.faceslim_donation) that 
> Original version cannot be published because it was violating the rules of the store.

Maybe we could discuss about it ? If not, this bug could at least explain why this app is not on Play Store.

Regards,
Axtux

**Comment by indywidualny** [comment]
It's not published there because Google decided to remove it (without any explanation). Now the package is blocked and I cannot add it again. I'm also afraid to do so (publish a different package) in order to avoid account termination.

They made it clear they don't want my app. Apparently I was impersonating Facebook Inc. which is not true. The name was different, the description had a disclaimer that's not an official app...

**Comment by jidanni** [comment]
Maybe since you fixed the name it will be OK now.
I can't use F-droid because it takes hours ti finish its internal computations loops.

**Comment by jidanni** [comment]
Hours to finish

**Comment by jidanni** [comment]
And… a PAID version of an "illegal" package would certainly be even more illegal than a FREE version of the exact same package…

**Comment by jidanni** [comment]
If possible please also make a standard Google Plus testers group so we can get testing versions automatically.

**Comment by indywidualny** [comment]
Yes but I would have to change a package name. It's easy because I can just use build flavors.

I'm just afraid... I don't want to be banned... Too afraid to do it. I have published some apps and account termination would be a disaster.

**Comment by axtux** [comment]
I've read some feedback from Play Store developer and I understand you are afraid. It seems they don't tell you precisely why they removed your app, making it really hard to correct it. And if you don't submit your app again without fixing what they want, chances are high they ben you ...

Maybe you could just create new Gmail account to publish this application ? Like that, you wouldn't care about it to be banned.

**Comment by indywidualny** [comment]
They are too smart to accept such a trick. They ban all the accounts
somehow related to the one which gets banned. I mean the same IP address,
similar location... And you can loose more than a dev account. All your
Google Accounts too, so pretty much everything. So it's not worth the risk
:) And it would cost me additional 25$ to open new dev account now.

niedz., 12.06.2016, 21:06 użytkownik Axtux <notifications@github.com>
napisał:

**Comment by Champion0081** [comment]
Guys, we need it on Google Play, any ideas?
