### ISSUE TITLE
Facebook killed the RSS 

### ISSUE THREAD

**Issue by creativetrendsapps** [indywidualny/FaceSlim#173]
Facebook has killed notification RSS feeds. Notifications no longer work, only messages will work now.

**Comment by indywidualny** [comment]
I truly hate those guys. This sucks.

śr., 8.06.2016, 08:13 użytkownik Jorell Rutledge <notifications@github.com>
napisał:

**Comment by creativetrendsapps** [comment]
Parsing notifications like messages should solve this. I worked on a solution yesterday that worked but needs to be polished

**Comment by indywidualny** [comment]
But it may cause heavy network usage...

Has anyone any idea how to implement it differently? :)

**Comment by creativetrendsapps** [comment]
How much data do message notifications use? I have notifications working thanks to the Swipe developer, but Notifications keep repeating for already checked notifications. I'm trying to find a way to fix that :-(.

**Comment by creativetrendsapps** [comment]
Hey, check out this revised code for notifications:

https://gist.github.com/creativetrendsapps/da211dd75cfb4af4cb79

**Comment by indywidualny** [comment]
Thanks. You should probably save the response to shared prefs and don't display a notification again when there is exactly the same string in another response ;)

**Comment by creativetrendsapps** [comment]
Tried already, cannot figure out how to save it.

**Comment by indywidualny** [comment]
Probably this way :D

`preferences.edit().putString("KEY", response).apply();`

**Comment by indywidualny** [comment]
Thanks. I did it - https://github.com/indywidualny/FaceSlim/releases/tag/v2.6.0-beta3

Have a look at "duplicates" solution:
https://github.com/indywidualny/FaceSlim/blob/3892497e91b0f818ada20c53c947e5a83dfd62fc/app/src/main/java/org/indywidualni/fblite/service/NotificationsService.java#L235-L237

**Comment by creativetrendsapps** [comment]
Good work! Works perfectly in Face Slim.

**Comment by creativetrendsapps** [comment]
Notifications are still being repeated.

**Comment by creativetrendsapps** [comment]
Yeah, I've actually just fixed this. This is because element.text() actually also contains a timestamp (i.e. someone liked your post. 5 minutes ago). Now if I saved that into UserPrefs as the last notification, checking for that the next time doesn't work because it's the same notification but "Just now" is now "5 minutes ago", meaning lastNotif == element.text() always returns false.

The solution for this is adding this little bit in the beginning of onPostExecute: 
String notifTime = result.select("span.mfss.fcg").text();
String notifText = result.text().replace(notifTime, "");
This will get the timestamp suffix and remove it from the notification text. Then you just use the notifText string going forward instead of result.text()

This should fix all of that though. Hope that somewhat makes sense!

**Comment by indywidualny** [comment]
Thanks! :)

pon., 13.06.2016, 00:19 użytkownik Jorell Rutledge <notifications@github.com>
napisał:

**Comment by indywidualny** [comment]
Release Candidate - https://github.com/indywidualny/FaceSlim/blob/ecd8dfc7873faf12063a7871d7000e45f2079686/app/app-release.apk

I will play with it today to make sure everything is 100% ok.

**Comment by creativetrendsapps** [comment]
The notifications work great. Only thing is message notifications repeat sometimes. Things seem to be running smoothly though.

**Comment by indywidualny** [comment]
Yep. Message notifications need to be clicked to be cancelled. It's the
only way because I'm reading only their number. OK. So it's ready. Btw,
updates are checked every 12 hours when you start the app.

pon., 13.06.2016, 03:36 użytkownik Jorell Rutledge <notifications@github.com>
napisał:
