### ISSUE TITLE
Facebook 'killed' the chat

### ISSUE THREAD

**Issue by faan11** [indywidualny/FaceSlim#174]
Without messenger, there is no way to access to the chat. Is there any way to avoid the installation of that horrible closed source app?

**Comment by dic1911** [comment]
use basic version on facebook and message function is working fine there(ugly tho)

**Comment by indywidualny** [comment]
You can also try "Messages" menu item from the drawer menu. It opens web messenger.

**Comment by faan11** [comment]
i tried with Messages but i only see images without text.
basic version? you mean the desktop version?  :S

**Comment by port3306** [comment]
you can use the normal chat on touch.facebook.com with the user agent from firefox on desktop. You must not use the site m.facebook.com for the chat. please add a setting point on face slim for change the user agent.

**Comment by dic1911** [comment]
@faan11 no, not desktop version, it's called "Basic mode" in English ver. of FaceSlim

**Comment by bastadur** [comment]
@port3360 Yeah, the developer of swipe for facebook app did that apparently and messages work on that app. Maybe indywidualny can do the same thing with faceslim.

**Comment by indywidualny** [comment]
Soon you will be able to set your own User Agent. There is also touch.facebook added. It's already in the repository. It needs to be tested but it looks promising.

**Comment by jidanni** [comment]
I cannot find your latest apk. When you say "in the repository" does that mean you have made an apk?
I cannot use monster F-droid.

**Comment by jidanni** [comment]
Please make a directory other than
https://github.com/indywidualny/FaceSlim/releases
so we can download the very latest testing version.

**Comment by homersimpsons** [comment]
There is this app on F-Droid : [Messenger bypasser (Redirects "OpenFB Messenger" intents to the web chat)] (https://f-droid.org/app/org.surrel.messengerbypasser)

**Comment by jidanni** [comment]
Thanks Homer but installation fails in the  package analysis phase. At least on ice cream sandwich.

**Comment by homersimpsons** [comment]
It doesn't failed for me, but this doesn't work with FaceSlim... A solution is to change user agent

**Comment by indywidualny** [comment]
Test version today. I have to build it and upload it.

niedz., 12.06.2016, 15:33 użytkownik homersimpsons <notifications@github.com>
napisał:

**Comment by indywidualny** [comment]
https://github.com/indywidualny/FaceSlim/releases/tag/v2.6.0-beta1

**Comment by indywidualny** [comment]
Mozilla/5.0 (Windows NT 6.1; WOW64; rv:40.0) Gecko/20100101 Firefox/40.1

It seems to resolve messages issues.

**Comment by indywidualny** [comment]
https://github.com/indywidualny/FaceSlim/releases/tag/v2.6.0-beta3

Please check it out. If it's not buggy I will release it tomorrow.

**Comment by schmatzler** [comment]
The chat also works with the Blackberry 10 useragent string:
Mozilla/5.0 (BB10; Kbd) AppleWebKit/537.10+ (KHTML, like Gecko) Version/10.1.0.4633 Mobile Safari/537.10+

No need to enable to touch.facebook.com. Blackberry doesn't have Messenger support, so I guess they decided to suppress the "Please install Messenger" popup.

**Comment by indywidualny** [comment]
Awesome!

niedz., 19.06.2016, 01:55 użytkownik Ronny Schmatzler <
notifications@github.com> napisał:
