### ISSUE TITLE
Way to access the chat in normal mode

### ISSUE THREAD

**Issue by Dostoi** [indywidualny/FaceSlim#175]
So I noticed that if you follow those step you can use the chat in normal mode. And I wonder if the app can't be changed to allow using it in normal mode.
If you enable facebook basic, then reload the page without quitting the app at any time, you can still use the normal interface and be able to access your message.

Can the app be changed to make it thinbk that it's in basic mode when you clic on the message icon ?

**Comment by MrGabigoo** [comment]
Actually I found that if loading the mobile version of messages (https://m.facebook.com/messages) with a desktop user agent it works perfectly

**Comment by port3306** [comment]
you can use the normal chat on touch.facebook.com with the user agent from firefox on desktop. You must not use the site m.facebook.com for the chat. please add a setting point on face slim for change the user agent.

**Comment by MrGabigoo** [comment]
Oops, actually meant touch.facebook.com, not m.facebook.com. You're right.

**Comment by indywidualny** [comment]
Ok. Custom user agent coming tomorrow. I should po probably add an option to choose touch.facebook as a default start page.

**Comment by indywidualny** [comment]
Ok, it's ready to test.

**Comment by MrGabigoo** [comment]
From my understanding, touch is especially for smartphones, while m sometimes loads as a basic view, depending on the user agent.

**Comment by indywidualny** [comment]
https://github.com/indywidualny/FaceSlim/releases/tag/v2.6.0-beta1

**Comment by MrGabigoo** [comment]
Tested that release and tried a few things. 

The chat works exactly as it used to before Facebook did the whole messenger thing when setting the user agent to this: 

"Mozilla/5.0 (Windows 7) AppleWebKit/536.26 (KHTML, like Gecko)"

**Comment by indywidualny** [comment]
I found a solution too #174
Now the only problem are notifications. I really have no idea how to implement it properly. It should be released anyway for now.

**Comment by MrGabigoo** [comment]
But then you might want to set an option for custom user agent but with that user agent as a "recommended" one, right?

**Comment by indywidualny** [comment]
Yep. It may be set for default until someone decides to change it. The
easiest way to do it.

niedz., 12.06.2016, 16:43 użytkownik Gabriel Bugeaud <
notifications@github.com> napisał:

**Comment by indywidualny** [comment]
https://github.com/indywidualny/FaceSlim/releases/tag/v2.6.0-beta3

If it's not buggy i will release it tomorrow.

**Comment by MrGabigoo** [comment]
Used it for a while and fiddled with things. Looks ready for release to me
