### ISSUE TITLE
2.5.2 same signature

### ISSUE THREAD

**Issue by jidanni** [indywidualny/FaceSlim#177]
One cannot download 2.5.2 from GitHub and install it over 2.5.0 because it has the same signature. One must use F-droid.

**Comment by indywidualny** [comment]
Yes. F-droid has a different signature than GitHub version. I cannot do
anything about it. They build the app independently when new release is
observed. Unfortunately I don't have access to their key, they don't have
access to my key.

niedz., 12.06.2016, 10:03 użytkownik Dan Jacobson <notifications@github.com>
napisał:

**Comment by jidanni** [comment]
The error message said "same signature" not different signature. But
this is Chinese Ice Cream Sandwich.
OK I figured out if I delete all of F-droid's data before running update
each time, I can still use F-droid.
