### ISSUE TITLE
90 degrees

### ISSUE THREAD

**Issue by jidanni** [indywidualny/FaceSlim#180]
Now the icons are 90 degrees off of the top bar… app unusable! 2.6.0.

**Comment by jidanni** [comment]
Tough to attache photos , sorry.

**Comment by indywidualny** [comment]
Try this user agent please: 

`Mozilla/5.0 (FuckMessenger 1.0; Mobile; rv:41.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.75 Safari/537.36`

Better?

**Comment by jidanni** [comment]
It turn out that the third preference, navigation at top, needs to be checked!

**Comment by indywidualny** [comment]
I'm glad it's resolved :)

śr., 15.06.2016, 11:00 użytkownik Dan Jacobson <notifications@github.com>
napisał:

**Comment by jidanni** [comment]
Its OK now (except can't get messages. But that is a different bug.)
Anyway: Please have some radio buttons with some important User-Agent strings,
and then even have a few empty radio buttons where the user can fill in his favorite agents, so he can easily toggle/try each.

**Comment by indywidualny** [comment]
That's a nice suggestion. Thanks. I will add it next time :)

czw., 16.06.2016 o 08:34 użytkownik Dan Jacobson <notifications@github.com>
napisał:

**Comment by zanzani** [comment]
For me, I still suffer from the 90deg issue I believe. No matter what setting. And it seems like the header of a message only has one column to use:
![screenshot_2016-06-17-07-45-19](https://cloud.githubusercontent.com/assets/19995184/16151114/774e8a70-349b-11e6-8a16-8a4b7e317d42.png)

**Comment by schmatzler** [comment]
Same problem here with Android 4.3 (if that's important).

The only solution is to use the simple version of the website.

**Comment by schmatzler** [comment]
I fixed it by using the useragent string for BlackBerry 10:

Mozilla/5.0 (BB10; Kbd) AppleWebKit/537.10+ (KHTML, like Gecko) Version/10.1.0.4633 Mobile Safari/537.10+

**Comment by indywidualny** [comment]
This one is great. Everything works as expected. Thanks. It should be the
default one and it will be.

niedz., 19.06.2016, 01:53 użytkownik Ronny Schmatzler <
notifications@github.com> napisał:

**Comment by indywidualny** [comment]
So everything is fixed. Awesome!
