### ISSUE TITLE
README don't describe FaceSlim properly

### ISSUE THREAD

**Issue by bart9h** [indywidualny/FaceSlim#185]
It says "Detailed description and more information below",
but there's only the Changelog, Screenshots and donation sections bellow.

**Comment by indywidualny** [comment]
Isn't that enough? Changelog says pretty much everything about all the
features. Just read from the bottom.

czw., 23.06.2016, 19:10 użytkownik Rodolfo Borges <notifications@github.com>
napisał:

**Comment by bart9h** [comment]
I think it is not enough.

Reading the changelog from the bottom will give you an idea of FaceSlim's features, but it is not obvious for an unsuspecting visitor, and it still doesn't describe _what FaceSlim is_.

**Comment by indywidualny** [comment]
Thanks. Now it's more clear what the app is.
