### ISSUE TITLE
F-droid doens't push the new release

### ISSUE THREAD

**Issue by Dostoi** [indywidualny/FaceSlim#187]
The f-droid version is still 2.6.0 even though there's 2 new version after this one.

**Comment by indywidualny** [comment]
Yes. They cannot build for API 24 yet. I hope they will do something about
it soon. Let's wait for a few days more. They are working on it.

niedz., 26.06.2016, 23:20 użytkownik Dostoi <notifications@github.com>
napisał:

**Comment by Dostoi** [comment]
Ok nice to know it

**Comment by indywidualny** [comment]
https://gitlab.com/fdroid/fdroidserver/merge_requests/140

It should be built tomorrow morning. API 24 has just been added.

**Comment by akrus** [comment]
Nothing yet :(

**Comment by indywidualny** [comment]
Yes, it's still something wrong - https://f-droid.org/forums/topic/face-slim-out-of-date/

**Comment by mvdan** [comment]
Builds are finally succeeding. Should be out tomorrow.

**Comment by indywidualny** [comment]
Yes. Everything is ok now :)
https://f-droid.org/wiki/page/org.indywidualni.fblite/lastbuild_42
