### ISSUE TITLE
Basic mode + Dark theme become unchangeable

### ISSUE THREAD

**Issue by hejops** [indywidualny/FaceSlim#189]
I turned on dark theme, followed by basic mode, and the result is that both become greyed out.

**Comment by indywidualny** [comment]
It's very rare and very strange bug. Those two options cannot be enabled simultaneously. When one is activated the second one gets grayed out. Somehow this mechanism didn't work for you and two of them were blocked. The fastest solution is just clearing app data. It shouldn't happen next time. This situation is extremely unfortunate but it's not actually a real bug. Something strange happened during saving preferences. More like an I/O system rare bug.

**Comment by hejops** [comment]
Fair enough. Perhaps the warning could include how to get out of such a situation as well (as you mentioned).
