### ISSUE TITLE
downloaded images saved with lots of extra characters

### ISSUE THREAD

**Issue by Walker7401** [indywidualny/FaceSlim#196]
Hi,
In previous Version (before 2.8.0),save images had the Facebook style filename, now they are saved with a filename like IMG_DATE-TIME.JPG which looks like IMG_18.07.2016-18:23:24.jpg
With a filename like this it is not possible to move the file to sdcard or to PC. Please retain old style filenames.

**Comment by indywidualny** [comment]
I don't understand why it's not possible to move the file. A file name is irrelevant. It has nothing to do with file operations...

I assume you are using a strange file manager but it's still extremely weird.

Those names seemed to be nice because it's more informative then just a random string of characters. You know exactly when the file was saved without even opening it.

**Comment by dic1911** [comment]
I might know why, because Windows doesn't allow a file named with symbols
like ":"

2016-07-21 2:22 GMT+08:00 Krzysztof Grabowski <notifications@github.com>:

**Comment by indywidualny** [comment]
Ok. It seems to be an explanation. Ok, so I will change a separator.

czw., 21.07.2016, 06:23 użytkownik Dic <notifications@github.com> napisał:

**Comment by Walker7401** [comment]
by the way, it's not (only) windows that does not allow ":", also Android lets move files with that characters to external SD card (mine is FAT-something, encypted by Android) - that does not depend on any kind of filemanager. 
Having had the original facebook-filenames seemd better because I could compare files (on different machines, dirs, etc) quick and easy by the filename, now I have to compare them by other means.
Why did you change filename formatting anyway?

**Comment by indywidualny** [comment]
I completely don't remember changing anything. I have to go through Git
commits and figure it out :) I got an idea to let user decide what filename
will be used. I will probably introduce it some day.

czw., 21.07.2016, 09:43 użytkownik Walker7401 <notifications@github.com>
napisał:

**Comment by Walker7401** [comment]
That would of course be a good idea. Thanks for answering so quick.

**Comment by tracker1** [comment]
why node just `faceslim-saved-image-YYYYMMDDhhmmss.ext`

**Comment by indywidualny** [comment]
Feel free to pull request it :)

https://github.com/indywidualny/FaceSlim/blob/master/app/src/main/java/org/indywidualni/fblite/activity/MainActivity.java#L1127

I'm currently thinking about letting user to choose.

niedz., 24.07.2016, 00:21 użytkownik Michael J. Ryan <
notifications@github.com> napisał:
