### ISSUE TITLE
How long does it take for new releases to be available in F-Droid?

### ISSUE THREAD

**Issue by dAnjou** [indywidualny/FaceSlim#200]
Hi,

I highly appreciate the effort you're putting into this app. Thank you very much for that!

See question in title please.

Cheers

**Comment by indywidualny** [comment]
One day. Sometimes several hours.

But now (and last time) F-Droid is stuck again because they're using
outdated tools and they cannot build the app.

czw., 4.08.2016, 12:35 użytkownik Max Ludwig <notifications@github.com>
napisał:

**Comment by dAnjou** [comment]
Thanks for the quick response. I found the forum thread and the F-Droid issue.

For Googlers: https://f-droid.org/forums/topic/face-slim-out-of-date/ and https://gitlab.com/fdroid/fdroidserver/issues/187
