### ISSUE TITLE
Unable to use Multi-factor authentication

### ISSUE THREAD

**Issue by YogliB** [indywidualny/FaceSlim#203]
Using FaceSlim from F-Droid (2.9.0) on CyanogenMod 13.1.
Trying to connect to my account brings me here:
https://pixel.facebook.com/si/kappa/?Ko=p

**Comment by indywidualny** [comment]
Ok. I will unlock this domain and it should be fine. It will be released soon.

**Comment by indywidualny** [comment]
Or not. I see the app tries to open it normally so it's not blocked. Have you tried to login and after the failure restarted the app? It may help as well. Logging in may be OK but you may not be properly redirected after the procedure.
