### ISSUE TITLE
Is the project alive?

### ISSUE THREAD

**Issue by timofonic** [indywidualny/FaceSlim#205]
I'm not a fan of Facebook and really hate their gambling algorithms, but sometimes I get to use it. On PC there's the possibility to reduce their crap by using a tonload of userscripts and extensions on Palemoon/Firefox, but FaceSlim is the only way on Android.

Is this project alive? How could it gain more developers to not suffer the line developer syndrome?

**Comment by krayon** [comment]
@timofonic I too sadly have no choice but to use Facebook at times and use this app to do so. Not sure what you want from this project but it's very much still under active development. As you can see from the code base the last commit was 12 days ago.

**Comment by indywidualny** [comment]
Yep. It's alive but I didn't do much lately.
