### ISSUE TITLE
Name „Messages” to something more informative.

### ISSUE THREAD

**Issue by alekksander** [indywidualny/FaceSlim#206]
Sliding menu „messages” position should indicate somehow that we are going to be redirected to messenger.com version of chat. Perhaps it shouldn't be in between names that are related to regular facebook.

**Comment by Lubieerror** [comment]
Not big problem but I think little bit this same. For me "Messenger" would be fine. I think even redirecting from old messages tab (on FB bar) would be good since FB has blocked it and there is no much hope for get it back (possibly that function would be disabled in settings).

**Comment by indywidualny** [comment]
"Old" messages tab is working ok with the latest version of the app. It uses a different User Agent (Blackberry one) in order to force this page. Try it :)

Ok, I will change "Messages" string to "Messenger".
