### ISSUE TITLE
Issue with notifications

### ISSUE THREAD

**Issue by ZeeRooo** [indywidualny/FaceSlim#214]
Hello, im trying to port this notifications to my app (isnt in play store, is for past my time). My problem is this: 

_10-08 23:06:38.452 31967-31967/me.zeeroooo.materialfb I/NotificationsService: ********** Service created! **********
10-08 23:06:41.458 31967-32308/me.zeeroooo.materialfb I/NotificationsService: Time interval: 120 seconds
10-08 23:06:41.463 31967-32308/me.zeeroooo.materialfb I/NotificationsService: RuntimeException caught
10-08 23:06:41.468 31967-31967/me.zeeroooo.materialfb I/NotificationsService: onDestroy: Service stopping...
10-08 23:06:41.474 31967-31967/me.zeeroooo.materialfb I/NotificationsService: ********** Service created! **********
10-08 23:06:44.480 31967-32384/me.zeeroooo.materialfb I/NotificationsService: Time interval: 120 seconds
10-08 23:06:44.489 31967-32384/me.zeeroooo.materialfb I/NotificationsService: RuntimeException caught
10-08 23:06:44.504 31967-31967/me.zeeroooo.materialfb I/NotificationsService: onDestroy: Service stopping...
10-08 23:06:44.518 31967-31967/me.zeeroooo.materialfb I/NotificationsService: ********** Service created! **********_

I dont know how to fix this, probably you can help me. The code is here: 
- https://github.com/ZeeRooo/MaterialFBook/commit/a846a11389538fe34c86d7c97af89b46e1107ebc
- https://github.com/ZeeRooo/MaterialFBook/tree/Testing

Thanks and sorry if this is a spam.

**Comment by indywidualny** [comment]
Run the app in Android debugger (Run -> Debug), set some break points (make a few red dots, clicking at the beginning of the line) before https://github.com/ZeeRooo/MaterialFBook/blob/a846a11389538fe34c86d7c97af89b46e1107ebc/app/src/main/java/me/zeeroooo/materialfb/Notifications/NotificationsService.java#L177

Then use the app and experiment with break points. You should be able to find the line which causes the exception. Or just show me a full stack trace of the exception. We need to know what causes it.

I may help you when it's clear what's wrong :)

**Comment by ZeeRooo** [comment]
If i put the break point above of live 177 i got: Service startes ............ service stoped and again..
When i put the break point in line 177+ i got: [http://imgur.com/a/XliUw](url)

Sorry haha im very noob in this :( but THANKS FOR THE HELP :)

**Comment by indywidualny** [comment]
Add `re.printStackTrace();` below `Log.i(TAG, "RuntimeException caught");` and you should know what's wrong.

**Comment by ZeeRooo** [comment]
Ohhhh thanks, i got this: _I/NotificationsService: ********** Service created! **********
I/NotificationsService: Time interval: 120 seconds
I/NotificationsService: RuntimeException caught
W/System.err: java.lang.SecurityException: ConnectivityService: Neither user 10309 nor current process has android.permission.ACCESS_NETWORK_STATE.
W/System.err:     at android.os.Parcel.readException(Parcel.java:1546)
W/System.err:     at android.os.Parcel.readException(Parcel.java:1499)
W/System.err:     at android.net.IConnectivityManager$Stub$Proxy.getActiveNetworkInfo(IConnectivityManager.java:957)
W/System.err:     at android.net.ConnectivityManager.getActiveNetworkInfo(ConnectivityManager.java:686)
W/System.err:     at me.zeeroooo.materialfb.Notifications.Connectivity.getNetworkInfo(Connectivity.java:21)
W/System.err:     at me.zeeroooo.materialfb.Notifications.Connectivity.isConnected(Connectivity.java:30)
W/System.err:     at me.zeeroooo.materialfb.Notifications.NotificationsService$HandlerRunnable.run(NotificationsService.java:153)
W/System.err:     at android.os.Handler.handleCallback(Handler.java:739)
W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:95)
W/System.err:     at android.os.Looper.loop(Looper.java:135)
W/System.err:     at android.os.HandlerThread.run(HandlerThread.java:61)
I/NotificationsService: onDestroy: Service stopping..._

Im going to chek it now... Thanks again :)

**Comment by indywidualny** [comment]
It's clear now. You need to add this permission to your AndroidManifest :)

**Comment by ZeeRooo** [comment]
YEAH!! Its working !!!!  :dancing_men:  :dancing_men:  :dancing_men: 

Thanks a lot :D !!!

**Comment by ZeeRooo** [comment]
_Im here again hahah... sorry_
i have a issue with notificationsservice.java and logger.java when i stop the app.
[http://i.imgur.com/4mvmEJB.png](url)

The code is here (same as FaceSlim) :P 
- Logger.java (Line 36): https://github.com/ZeeRooo/MaterialFBook/blob/master/app/src/main/java/me/zeeroooo/materialfb/Utils/Logger.java#L36
- Logger.java (Line 45): https://github.com/ZeeRooo/MaterialFBook/blob/master/app/src/main/java/me/zeeroooo/materialfb/Utils/Logger.java#L45
- NotificationsService (Line 78): https://github.com/ZeeRooo/MaterialFBook/blob/master/app/src/main/java/me/zeeroooo/materialfb/Notifications/NotificationsService.java#L78

I think; when i kill the app, the service of notif dont stop and i got force close, really i dont know.
Thanks for the patience :)

**Comment by indywidualny** [comment]
The context is wrong. You need to get application context from Application
class. Or try/catch it. Or just remove this Logger. It's not really needed.
I just wanted some debug info.

śr., 12.10.2016, 04:06 użytkownik Juan <notifications@github.com> napisał:
