### ISSUE TITLE
Not fit for normal use anymore

### ISSUE THREAD

**Issue by sirmacik** [indywidualny/FaceSlim#216]
Hi there!

I think that for a month now app became unusable but in different forms on different devices (steps to reproduce):
- moto g (peregrine CM13), gives no connection on every first try to load any facebook content
- sgs7 (stock), redirects to home on every try of adding someone to the event or editing it.

Full wipe and reinstallation haven't helped. I'd love to assist with debugging, just give me some instructions.

Cheers
Marcin

**Comment by landry314** [comment]
yep, pages refuse to load almost randomly all over facebook. i cant use it for events most of the time... most likely facebook sabotage. i hate them.

**Comment by tracker1** [comment]
Agreed, it is most likely fb sabotage... I hate their app, and really would love the original/old mobile UI... the user agent change is best bet.. have been seeing a few things that are now saying "you must use the facebook app to view this content"

**Comment by indywidualny** [comment]
It should be OK now. I mean with 3.0.0.

**Comment by sirmacik** [comment]
Works mostly ok. Sometimes it gives connection errors on some ad servers. I don't have ad-blocking enabled on my phone. But I think that this issue can be marked as solved. 

Cheers!
