### ISSUE TITLE
Installing FaceSlim Broke Facebook Events in Regular Browser

### ISSUE THREAD

**Issue by landry314** [indywidualny/FaceSlim#217]
This is bizarre. My friend installed the newest version of FaceSlim on her phone then when events weren't working she went to her normal stock android browser to get events on facebook.com but there too they just wouldn't load. How is this possible? I uninstalled FaceSlim for her and STILL events won't load in her browser. The only thing I can think of is that facebook is sabotaging her. Maybe they saw she installed FaceSlim and they are punishing her. Can someone please help??? I hate facebook.

**Comment by roelofr** [comment]
That appears to be an issue with the phone.

Has she tried turning it off and on again and does the problem persist after a reboot?

I just installed the app and everything seems to be working just fine on Chrome. Maybe post a bit more information (phone model, android version etc)

**Comment by landry314** [comment]
yes, we rebooted the phone.

we figured out that it was facebook sabotaging their mobile version again. they are trying to get everyone to install their app. it was the stock android browser in android 7. firefox too has this issue as well...

**Comment by landry314** [comment]
It is just that facebook refuses to fix their events problems in their mobile web version most likely to get people to install their spyware. This is not an issue with FaceSlim.
