### ISSUE TITLE
Privacy

### ISSUE THREAD

**Issue by moshpirit** [indywidualny/FaceSlim#219]
>FaceSlim is free of spyware, unlike what is built into the official Facebook and Facebook Messenger applications.

What spyware and what information sends to Fb? (Cookies, JS, location, proxy/TOR, ...) I'm trying to find the most "private" application for this

**Comment by rignaneseleo** [comment]
Installing Facebook app, you give that the permission to access to:

> ## Device & app history
> retrieve running apps
> ## Identity
> find accounts on the device
> add or remove accounts
> read your own contact card
> ## Calendar
> read calendar events plus confidential information
> add or modify calendar events and send email to guests without owners' knowledge
> ## Contacts
> find accounts on the device
> read your contacts
> modify your contacts
> ## Location
> approximate location (network-based)
> precise location (GPS and network-based)
> ## SMS
> read your text messages (SMS or MMS)
> ## Phone
> directly call phone numbers
> read call log
> read phone status and identity
> write call log
> ## Photos/Media/Files
> read the contents of your USB storage
> modify or delete the contents of your USB storage
> ## Storage
> read the contents of your USB storage
> modify or delete the contents of your USB storage
> ## Camera
> take pictures and videos
> ## Microphone
> record audio
> ## Wi-Fi connection information
> view Wi-Fi connections
> ## Device ID & call information
> read phone status and identity
> ## Other
> download files without notification
> adjust your wallpaper size
> receive data from Internet
> view network connections
> create accounts and set passwords
> read battery statistics
> send sticky broadcast
> change network connectivity
> connect and disconnect from Wi-Fi
> expand/collapse status bar
> full network access
> change your audio settings
> read sync settings
> run at startup
> reorder running apps
> set wallpaper
> draw over other apps
> control vibration
> prevent device from sleeping
> toggle sync on and off
> install shortcuts
> read Google service configuration

We cannot see the source file of the app and when this permission are used, and mostly **how this information are managed**.

**Comment by indywidualny** [comment]
That's right! Official Facebook app makes me frightened. It just can do everything. And this app uses only those: https://github.com/indywidualny/FaceSlim/blob/master/app/src/main/AndroidManifest.xml#L7-L15

**Dangerous Permissions** are optional and you can block them anytime.
* Write permission to save files, upload images, save logs if you decided to.
* Location permission if you want to check-in which is disabled by default.

Normal Permissions don't even need to be explained. Their names are self-explanatory.
