### ISSUE TITLE
Support for Chromecast on videos

### ISSUE THREAD

**Issue by gheesh** [indywidualny/FaceSlim#220]
Could you please add support for Google Chromecast when playing videos?

Thank you!

**Comment by creativetrendsapps** [comment]
From my understanding Chhromecast is only available through Chrome based browsers and available through WebView apps.

**Comment by indywidualny** [comment]
Casting is only supported in Chrome or Chrome Custom Tabs. Not webview or at least I didn't find any information about it. So no way for now.
