### ISSUE TITLE
No differentiation between read/unread in dark-themed notification drawer

### ISSUE THREAD

**Issue by Dhraakellian** [indywidualny/FaceSlim#227]
As of 3.0.0, I cannot see any indication at all of which notifications are read or unread while using the dark theme.
In previous versions, there would be a white/light-colored line above each read notification, which was usable, if not ideal.
Would it be possible to give the dark theme different read and unread colors like the light theme has?

Phone info:
Phone: Samsung Galaxy S5 (SM-G900T)
OS: CyanogenMod 13, Android 6.0.1
System theme: Deep Darkness variants. Also tested with CM default.

**Comment by indywidualny** [comment]
@Dhraakellian Is it ok now? https://github.com/indywidualny/FaceSlim/commit/b764849856d1280294f1ded7dcc5045199d199a1 If so I'm publishing it (by adding release tag). It's gonna be this exact build.

**Comment by Dhraakellian** [comment]
That appears to have done the trick. Thanks.
