### ISSUE TITLE
Tor functionality removed?

### ISSUE THREAD

**Issue by Nutomic** [indywidualny/FaceSlim#229]
It looks like you removed all the code for Tor connections in 826d15a8f92a02c0ada258c1ef9092e364851a84. Why is that?

**Comment by indywidualny** [comment]
Unfortunately I wasn't able to make it work. I tried for a long time and it just didn't. Perhaps it's was only a problem with Android Nougat but still. Nougat is the current Android version and all the latest phones are released with Nougat. It means the option was unreliable.

I will create another branch and try to add this code there. Perhaps with your help we will manage to do it. But I'm only saying that I've installed TOR and the connection wasn't tunneled at all. So it's not the code for Master branch for sure.

**Comment by Nutomic** [comment]
I've never experienced any problems with Tor, even on Android 7. How about leaving Tor as an experimental option, maybe with a warning dialog?

Did you find anything in the logs when you tried it?

**Comment by nvllsvm** [comment]
Why not use [Orbot](https://guardianproject.info/apps/orbot/) instead? Seems silly to have Tor built into a wrapper app for a service notoriously invasive of privacy.

**Comment by nvllsvm** [comment]
Why should Tor be a part of a wrapper app to a service which notoriously is not privacy friendly? 

[Orbot](https://guardianproject.info/apps/orbot/) should be used instead.

**Comment by tristan-k** [comment]
Please bring this back. It's a pain in the ass to route FaceSlim through tor if using Afwall+ as well.
