### ISSUE TITLE
White pages - more

### ISSUE THREAD

**Issue by gsantner** [indywidualny/FaceSlim#231]
`sync.liverail.com` is also a page causing white pages sometimes

<img src="https://cloud.githubusercontent.com/assets/6735650/21815407/c2ddbc40-d75c-11e6-88b1-a5cddf00fd07.png" width="40%" height="40%" />

This is a domain owned by Facebook and part of their monetizing platform.
<https://whois.domaintools.com/sync.liverail.com>

**Comment by indywidualny** [comment]
I will white list it then.
