### ISSUE TITLE
News feed blank

### ISSUE THREAD

**Issue by jidanni** [indywidualny/FaceSlim#237]
News Feed  just shows content very briefly and then just becomes a mostly blank white screen.

**Comment by indywidualny** [comment]
Always or just one time? Apparently Facebook sometimes tries to connect to some sites and when it's not able to, you see a white screen.

I've allowed some problematic domains to get rid of the problem:
https://github.com/indywidualny/FaceSlim/commit/4201ab948981efae459758d1f906d5e65ec0cfb0#diff-6d2646f54d67a1b7cc40bd7b431817faR104

but you need to also white-list them in your ad-blocker if you use any. That's what I found out.

**Comment by jidanni** [comment]
I don't use an adblocker and the problem persists with 3.0.3. (See everything, then
suddenly the body below the blue header becomes blank.)

Maybe there should be an advanced option menu of the problem domains so
the user can adjust the defaults to see if the problem will go away
instead of hardwiring them in.)

**Comment by jidanni** [comment]
![screenshot_20170201-221248](https://cloud.githubusercontent.com/assets/1230959/22510166/7f3db4ee-e856-11e6-9c2d-e0b7a097279f.jpg)

**Comment by jidanni** [comment]
Wait. I had "hide newsfeed" enabled!
So you need to put some words into that big blank area saying that hide Newsfeed has been enabled in face slim so therefore there's a big blank area. Thank you.

**Comment by indywidualny** [comment]
Ok. So resolved. Nice.

**Comment by jidanni** [comment]
Besides putting some words in that big blank area saying that the user himself has disabled it, you also need to note in the settings that one must terminate the app and restart it in order to restore the news feed.
