### ISSUE TITLE
App version unavailable within app

### ISSUE THREAD

**Issue by jidanni** [indywidualny/FaceSlim#238]
Be sure to put the app version number somewhere available within the apps menus.

**Comment by indywidualny** [comment]
But it's right there, on About page :)

**Comment by jidanni** [comment]
No other app out of four thousand puts it on the very bottom without any
text saying what it is etc. and expects anybody to guess/find/etc.

**Comment by jidanni** [comment]
Say:
Version                 3.0.2
there.

**Comment by indywidualny** [comment]
Ok, sure :)
