### ISSUE TITLE
White screen on messages

### ISSUE THREAD

**Issue by ZeeRooo** [indywidualny/FaceSlim#240]
When you open a link in chat and go back, we got a white screen. Any url is not decoded.

**Comment by indywidualny** [comment]
And what about back button twice? Did it help?

**Comment by ZeeRooo** [comment]
Yes, touching 2 times the back button it works.

**Comment by indywidualny** [comment]
So my answer for now is just to do it twice. No idea why it's happening but I will think about it.

**Comment by ZeeRooo** [comment]
It looks like cleanAndDecodeUrl isnt working. Maybe because it redirects to http**s**://lm.facebook and no to http://lm.facebook like is write in Miscellany.java

**Comment by ZeeRooo** [comment]
I builded Folio v.9 and have the same issue. But in the latest version avaible in Play Store (v.10) this is fixed. The github´s page isnt up to date to see.

**Comment by indywidualny** [comment]
Perhaps I found the problem :) Let's see, next release soon.

**Comment by ZeeRooo** [comment]
Yes, it worked for me. Good job +1

**Comment by ZeeRooo** [comment]
The line who solved the issue is `.replace("https://lm.facebook.com/l.php?u=", "")` Only with this line the problem are fixed. (Same issue in other pages are fixed with this code too). Congrats

**Comment by indywidualny** [comment]
Here is beta signed with release key if you want to update right away https://github.com/indywidualny/FaceSlim/commit/c651fc166e24746564ccd9e22330087ecf4be4e5#diff-eaf6f3fdbbdebb72a8b12b998334cd8d

So  https://github.com/indywidualny/FaceSlim/commit/f0598d4c362745bb0933f9c9b9f15a081323686f was not necessary?

**Comment by ZeeRooo** [comment]
You can delete the following lines:
https://github.com/indywidualny/FaceSlim/blob/f0598d4c362745bb0933f9c9b9f15a081323686f/app/src/main/java/org/indywidualni/fblite/webview/MyWebViewClient.java#L100

https://github.com/indywidualny/FaceSlim/blob/796d48b3402686aed26ba91fc80cb7cf99f80b28/app/src/main/java/org/indywidualni/fblite/util/Miscellany.java#L25

https://github.com/indywidualny/FaceSlim/blob/796d48b3402686aed26ba91fc80cb7cf99f80b28/app/src/main/java/org/indywidualni/fblite/util/Miscellany.java#L28


**The only line what you need is;**
https://github.com/indywidualny/FaceSlim/blob/796d48b3402686aed26ba91fc80cb7cf99f80b28/app/src/main/java/org/indywidualni/fblite/util/Miscellany.java#L24

**Comment by indywidualny** [comment]
Thanks for your help :) I will move it to master in the morning and release it.

**Comment by ZeeRooo** [comment]
No problem. You help me many times ;)
