### ISSUE TITLE
Notifications images

### ISSUE THREAD

**Issue by RujjhidHD** [indywidualny/FaceSlim#244]
Any way to get users image in the notification? eg: when a friend send me a message, display his profile picture into the notification.

**Comment by MikeKlem** [comment]
Liked

**Comment by indywidualny** [comment]
I will add it soon. But not for messages since I'm fetching unread messages number only anyway. Just for normal notifications.

**Comment by indywidualny** [comment]
It's working really nice :) Thanks for this suggestion 👍

**Comment by ZeeRooo** [comment]
Omg @indywidualny 
Its really cool. 
Im scheduling the notifications with Alarmmanager and IntentService (yes, without asynctask) right now, im testing and the consumption is less than a handler.

**Comment by RujjhidHD** [comment]
Ohhh thank you !!
I can not wait for the final release :)
