### ISSUE TITLE
Add "add to home screen" link

### ISSUE THREAD

**Issue by jidanni** [indywidualny/FaceSlim#247]
There already is a "Copy current URL" link  in the menu. However,  you need to add an  "Add to home screen" link just like the Google Chrome browser app has. Then we could create shortcuts much easier. PS be sure to allow the user to be able to adjust the link and the title of the link at all times if possible.

**Comment by jidanni** [comment]
Call it "Add current URL to home screen."

**Comment by indywidualny** [comment]
Sure.
