### ISSUE TITLE
Don't forget a link to Home

### ISSUE THREAD

**Issue by jidanni** [indywidualny/FaceSlim#249]
Just as important as Newsfeed in the panel of links would be a link to Home,
https://mbasic.facebook.com/home.php , etc.

**Comment by indywidualny** [comment]
What is the difference? It's exactly the same as news feed :D

**Comment by jidanni** [comment]
Hmmm, I see.
Well today on mbasic, I only see the word Home there on that page. Therefore you should call it "Home (News Feed)" or at least "News Feed (Home)".

**Comment by indywidualny** [comment]
Ok. Fair enough.

**Comment by jidanni** [comment]
Too bad no ALT text for those images.
