### ISSUE TITLE
This project should avoid the name FacebookLite or Facebook Lite

### ISSUE THREAD

**Issue by jidanni** [indywidualny/FaceSlim#25]
Wouldn't it be wise to read
https://www.facebookbrand.com/dos-donts
when considering to continue to use essentially the same name as
the https://www.facebook.com/lite/ product?

Legal battles with deep pockets corporations might not be advisable,
unless one is hoping for a financial settlement on "who came first" ...

Besides the legal issue, there is also the never ending confusion caused to new users, despite any disclaimer notices.

**Comment by juzman** [comment]
I agree. Maybe something like "Facebook Slim" would be better suited.

**Comment by G33KS44n** [comment]
I agree with you guys

**Comment by indywidualny** [comment]
Well. I will change the name in the future. I was first so the name is the same as the official Facebook product. It's a coincidence.

**Comment by jidanni** [comment]
"Facebook Slight"
or best to avoid "Facebook" altogether?
"Fazebook..."
"Phacebook... "
Better search Google first to see if those have been used already too...

**Comment by indywidualny** [comment]
I'm thinking of the name "Facer". Seems unique and nice :) 

There is an app with the name "Facer Watch Faces" but it's a completely different project so it shouldn't be misleading.

**Comment by jidanni** [comment]
Also please add an article comparing the Facebook company's version and this project's version. Is there any reason for users to use one instead of the other, and which one.

**Comment by juzman** [comment]
@indywidualny "Facer" seems perfect! @jidanni I know the official "Facebook Lite" doesn't allow you to reply to comments, where as this one does. :)

**Comment by indywidualny** [comment]
#juzman Finally it's gonna be Facebook Slim. I just changed it and I will publish it next week. Slim is nice :)

**Comment by juzman** [comment]
@indywidualny Sounds good :+1: Will checkout github for any other changes too. :)

**Comment by jidanni** [comment]
Any chance of putting it on Google Play for easy updates?

**Comment by juzman** [comment]
@jidanni Install F-Droid for easy updates.

**Comment by indywidualny** [comment]
@jidanni Unfortunately not -  https://support.google.com/googleplay/android-developer/answer/2985871?hl=en

They removed it once and send me that link. Now I'm afraid I can be banned next time so I'm not doing anything stupid ;) 

(Semi) auto updates can be done through F-Droid client - https://f-droid.org/FDroid.apk
It's a really awesome way of updating apps from their database.

**Comment by jidanni** [comment]
OK I'll try F-Droid.

Actually even if you don't put it on Google Play, I am sure you will still run afoul of
https://www.facebookbrand.com/dos-donts .

Who can sleep easy at night worried that one day one will get a letter
from Facebook's lawyers?

Examining https://play.google.com/store/search?q=facebook
one sees that only their official apps start with "Facebook".

The others follow the format of "Slim for Facebook", etc.

**Comment by jidanni** [comment]
https://support.google.com/googleplay/android-developer/answer/2986098 , a good read, even though you don't intend to put it on Google Play.

**Comment by indywidualny** [comment]
So I will avoid Facebook in my name. It's good I didn't changed it yet. Well, now I'm aware :) I just didn't know it before, when the app was published for the first time.

**Comment by indywidualny** [comment]
BTW. Do you like FaceSlim / Face Slim? Facer is actually not a good name after some time of thinking.

**Comment by juzman** [comment]
@indywidualny What about "FBSlim" It technically doesn't have the word "Facebook" in it. Just have the description as "FaceBook Slim". ;)

**Comment by indywidualny** [comment]
Ok, did it. Facebook lawyers are no longer my concern. Face Slim, because it looked the best on my apps list. I have to e-mail F-Droid and tell them to change the name in their repository. Update should be @ F-Droid in the morning. It's actually the same build as before. I just updated some libraries and targeted Marshmallow.

https://github.com/indywidualny/FaceSlim/releases/tag/v1.8.0

**Comment by juzman** [comment]
@indywidualny Yep, checked changes on github. :+1:

**Comment by indywidualny** [comment]
Ok, thank you for you attention and thanks for that trademark infringement warning @jidanni 
If something is wrong feel free to create another issue. Cya ;)

**Comment by jidanni** [comment]
Please close this bug when the new name is fully up and running on Fdroid … and Github.

**Comment by jidanni** [comment]
Please close this bug when the new name is fully up and running on Fdroid.

**Comment by indywidualny** [comment]
Ok. Everything is changed now. I just checked it out :)

**Comment by jidanni** [comment]
F-droid app only has old name!!!

**Comment by indywidualny** [comment]
Sorry but you are not right:

https://www.dropbox.com/s/xy4nknum1tc6eyw/Screenshot_2015-09-14-11-29-45.png?dl=0
https://www.dropbox.com/s/2gbw3jvnomenrvf/Screenshot_2015-09-14-11-30-14.png?dl=0

Please refresh f-droid database ;)

**Comment by jidanni** [comment]
https://drive.google.com/file/d/0ByOmuSSxHabMeWI5LTB5WUpoUVE/view?usp=docslist_api OK but why didn't it update automatically?

**Comment by jidanni** [comment]
Was it the 14?

**Comment by jidanni** [comment]
Can't move app to sdcard.

**Comment by jidanni** [comment]
www.quora.com/Why-cant-some-Android-apps-like-Facebook-or-WhatsApp-be-moved-to-the-SD-card-in-a-non-rooted-phone-Why-cant-developers-add-this-feature  but real FB lite can be moved.

**Comment by jidanni** [comment]
No icon put into launcher. And… 
!! Your "f" icon is just begging for their lawyers to swing into action!!

**Comment by jidanni** [comment]
98% same as real app… too coincidental!

**Comment by jidanni** [comment]
By launcher I mean no shortcut created.

**Comment by indywidualny** [comment]
Yes, you cannot move it to SD Card. It have to be installed into internal memory and it's small enough so it shouldn't be a problem. Otherwise notifications will not work so I blocked installing into SD Card.

About the icon - it's just the "f" letter in Helvetica or Roboto http://romannurik.github.io/AndroidAssetStudio/icons-launcher.html#foreground.space.trim=1&foreground.space.pad=0&foreColor=607d8b%2C0&crop=0&backgroundShape=square&backColor=ffffff%2C100&effects=none 
so it's 100% mine and whatever ^^
They changed their logo and colors recently (a little bit) so it's my, independent color.

But the issue is not really about it ;)

**Comment by jidanni** [comment]
Yes I am trying to reduce the confusion between the two projects. Your icon is 100 % the sane as theirs except for being more centered.

**Comment by indywidualny** [comment]
I will change it then. I will collect more issues and I will release a new version with a new icon and some fixes. I suppose it's gonna happen next month. I'm a little busy at the moment.

**Comment by jidanni** [comment]
OK.
https://www.facebookbrand.com/guidelines?asset=2&media=1,2,3
https://www.google.com/search?q=fs+logo&tbm=isch
