### ISSUE TITLE
Video uploads

### ISSUE THREAD

**Issue by creativetrendsapps** [indywidualny/FaceSlim#271]
Video uploads aren't available in the file chooser. Facebook allows video to be uploaded in the status updater, FaceSlim doesn't enable choosing video when tapping the video button, there's only images available.

**Comment by creativetrendsapps** [comment]
I enabled video uploads in a terrible way. Though I'll revisit this in a few hours.

**Comment by fcayre** [comment]
Any new @creativetrendsapps ? Haven't had any time to try another approach ?
Please update this thread if you do, I'm still interested ;-) !

**Comment by creativetrendsapps** [comment]
Sure, I'll take a look into it, hopefully by tomorrow sometime.

**Comment by creativetrendsapps** [comment]
@fcayre submitted a pull request.

**Comment by fcayre** [comment]
@creativetrendsapps thanks very much. Waiting for this fix to land in fdroid, which may happen in a while.

**Comment by indywidualny** [comment]
Done. Took a while. Sorry. I'm very busy recently.
