### ISSUE TITLE
easy way to go to the top

### ISSUE THREAD

**Issue by newbeewan** [indywidualny/FaceSlim#274]
Hi,
FaceSlim is a very usefull alternative to the fat facebook app.

A functionality is missing for me : an easy way to go to the top of the main page (like twitter by tapping on the tab)... Is there any possibilities to implement it ?

Regards

Mourad

**Comment by C0T0ZAK0T** [comment]
but there is option like that, in settings turn on navibar/buttons always on top and that works fine :)

**Comment by newbeewan** [comment]
Where is that setting ? I can't find it !

**Comment by C0T0ZAK0T** [comment]
correct me if im wrong, but propably 4th from top in settings

**Comment by newbeewan** [comment]
All right; I was looking into the facebook settings not in faceslim settings...

First, It was not working, it need application restart to work...

It's nice for me :)
