### ISSUE TITLE
messenger.com 

### ISSUE THREAD

**Issue by C0T0ZAK0T** [indywidualny/FaceSlim#277]
Witaj! Na wstępie chciałbym tylko powiedzieć - dobra robota! :)
A teraz do rzeczy, wysuwając panel boczny i klikając na Messenger.com wszystko pięknie się wyświetla, klikam 'Skopiuj Ten Adres' - kopiuje się właściwie, wszystko się zgadza i tu pójdę pytanie/problem: Po kliknięciu 'Dodaj Skrót Launchera' skrót się dodaje, ale po kliknięciu w niego zamiast okna messengera z wiadomościami pokazuje się reklama aplikacji i nie da się jej obejść, można coś na to poradzić?
(z góry przepraszam za zawracanie głowy głupotami)
Pozdrawiam :)

**Comment by Lubieerror** [comment]
Dla pewności - zmieniłeś User-Agenta?

(Jeśli się nie mylę to ten powinien być)
`Mozilla/5.0 (BB10; Kbd) AppleWebKit/537.10+ (KHTML, like Gecko) Version/10.1.0.4633 Mobile Safari/537.10+`

**Comment by C0T0ZAK0T** [comment]
wpisalem ten, nadal bez zmian - działa po kliknięciu, ale po ustawieniu launchera otwiera się automatycznie przekierowanie do strony z reklamą / prośbą o pobranie messengera

**Comment by indywidualny** [comment]
Tak. Klikanie w ten link Messenger.com jest specjalnie obsłużone, bo tam też trzeba dostawać się specjalnym sposobem. Zrobienie skrótu pozbawi nas tego triku i nie mamy dostępu. Jeśli chcesz mieć dostęp do wiadomości z poziomu swojego ekranu głównego to nie dodawaj, skrótu, a widget :) Na liście widgetów jest specjalna ikonka, która prowadzi właśnie do standardowych wiadomości.

**Comment by C0T0ZAK0T** [comment]
dzieki, solved :)
