### ISSUE TITLE
Feature request: reactions

### ISSUE THREAD

**Issue by CarbonFixer** [indywidualny/FaceSlim#284]
Currently, it is not possible from FaceSlim to choose reactions for facebook posts/comments other than the standard "Like". It would improve the standing of FaceSlim as a complete alternative to the official facebook app if this feature was available.

https://en.facebookbrand.com/assets/reactions

**Comment by indywidualny** [comment]
It is. Just long click like button :)

**Comment by CarbonFixer** [comment]
Oh. My bad. Thanks :)
