### ISSUE TITLE
App update fail and NA on F-Droid

### ISSUE THREAD

**Issue by silvioto** [indywidualny/FaceSlim#296]
First thanks for this great app, that is just I need!
I have version 3.2.0 installed from f-droid.
2 days ago FaceSlim show a new update available; I tried to install downloading the new 3.2.1 apk from github but it don't install with a generic message (X app not installed).
From F-Droid the new version 3.2.1 is not available.
Thanks.

**Comment by indywidualny** [comment]
Just wait a few more hours for F-Droid version. You cannot install GitHub version when you have F-Droid one :)

**Comment by silvioto** [comment]
Thanks very much. Now I understand how it works and I'm happy it is not an
issue.

Il 30 Set 2017 12:31, "Krzysztof Grabowski" <notifications@github.com> ha
scritto:
