### ISSUE TITLE
Can't wave back

### ISSUE THREAD

**Issue by jidanni** [indywidualny/FaceSlim#320]
When somebody waves at me in the messenger, I can't tap to wave back. Nothing happens.

**Comment by creativetrendsapps** [comment]
You cannot wave back without Facebook messenger.

**Comment by jidanni** [comment]
So what does FaceSlim do in other such cases where the user can't do something they are invited to do?

**Comment by creativetrendsapps** [comment]
FaceSlim is a wrapper for the Facebook mobile site. There are limitations with the Facebook mobile site.

**Comment by jidanni** [comment]
OK I passed the bug along to Facebook. They responded
```
Thank you for reporting this bug! We cannot respond individually to each report, but we would like you to know that your report will be used to improve Facebook.
```
So surely it will be fixed soon.
