### ISSUE TITLE
"share now" double-posts to timeline

### ISSUE THREAD

**Issue by Dhraakellian** [indywidualny/FaceSlim#321]
When doing _Share_ > _Share Now_, the post shows up in the timeline twice
work-around: _Share_ > _Write Post_ does not appear to be affected.

Mobile site reproducibility:
Does not happen with m.facebook.com in either Firefox 58.0.2 or Chromium 67.0.3369.0

FaceSlim version: 3.2.1 installed from f-droid
OS: Android 7.1.2 / LineageOS 14.1-20180316-NIGHTLY-klte (and some previous weekly builds)

**Comment by catb0t** [comment]
This is not specific to this application; it affects normal users on Facebook Web and Mobile App interfaces too; it is Facebook's problem.

**Comment by indywidualny** [comment]
Facebook issue. Their web interface is buggy on purpose. They want you to use their shitty app :/
