### ISSUE TITLE
Feature request: disable react sounds

### ISSUE THREAD

**Issue by josiahb** [indywidualny/FaceSlim#345]
FB recently changed such that reacts provide an audio notification. It would be nice to have an in-app way to disable them.

**Comment by wwwehr** [comment]
I just resolved this with [this pull request](https://github.com/indywidualny/FaceSlim/pull/347). cheers

**Comment by wwwehr** [comment]
hey guys - I made a build for my wife's phone, but I suggest that you wait until Mr. Krzysztof Grabowski creates an official version.

[Here's the file](https://drive.google.com/file/d/1fy7oTudQJvTNSfqxFIbtugvJJE97F8bh/view?usp=sharing) if you'd like.

Cheers,
-nicholas

**Comment by indywidualny** [comment]
I will try to find a moment tomorrow to build it. Ok.

**Comment by indywidualny** [comment]
Done :)
