### ISSUE TITLE
Force mobile site (touch.facebook.com) + Stories issue on mobile data

### ISSUE THREAD

**Issue by kowith337** [indywidualny/FaceSlim#359]
Note that may depend on users who got feature to open/upload stories without the need to use/install official app, include MESSenger and Facebook Lite.

### Steps to reproduce
1. Make sure you're logged in
2. Make sure you're connect to mobile data (especially if your operator support **Free Basics**)
   - You can determine by tap the menu in Facebook and you can see two menu (Free Basics and Facebook Free Mode) added
3. Set app to "Force mobile site"
4. Set this user agent > `Mozilla/5.0 (X11; Linux armv7l) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.77.34.5 Safari/537.36`
5. Try upload photo into your stories, or watch other people's stories

### Expected behaviour
You can upload and post stories or you can view other people's stories

### Actual behaviour
- You cannot view other stories
   - This can solve by refresh the page when it's show the "No internet connections" message.
- You cannot upload stories
   - Refresh the page doesn't help, a pre-publish UI that show uploaded images will gone.

### The cause
I've tested outside of your app, e.g. use Fenec F-Droid or IceCatMobile and spoof user agent for `touch.facebook.com` through `about:config` and found Facebook redirect some requests to `mobile.facebook.com` and may fail to receive referrer or header data because of cross origin domain policy.
However, I cannot reproduce issue when connect to Wi-Fi (Not mobile hotspot), also observed network log and found none of any attempts to redirect some requests to `mobile.facebook.com` while using on this kind of network.

**Comment by creativetrendsapps** [comment]
What is "Chrome/99.77.34.5 "?

**Comment by kowith337** [comment]
I've got the version number from Chromium "Content shell"

**Comment by creativetrendsapps** [comment]
@kowith337 that's odd. Chrome isn't close to version 99 as of yet.

**Comment by kowith337** [comment]
I realize this is an external problem that occur by Facebook and their Free Basics systems, seems like it's no point for here.
