### ISSUE TITLE
allow open item in new tab

### ISSUE THREAD

**Issue by jidanni** [indywidualny/FaceSlim#36]
Perhaps allow more than one 'tab' to exist at one time.

**Comment by indywidualny** [comment]
The app is supposed to be lightweight. I'm afraid new tabs mean another WebView and it's a quite heavy stuff. It have to be fast and responsive.

**Comment by jidanni** [comment]
Actually once "no way to return to all notifications #35" is solved this extra tab workaround wouldn't be as pressingly needed.
