### ISSUE TITLE
Why this app isn't in Google Play ?

### ISSUE THREAD

**Issue by the4anoni** [indywidualny/FaceSlim#362]
Hi developer :)
Please publish this app to G Play (I like auto updates without F-Droid).

**Comment by jidanni** [comment]
It violates the terms of service, or something.  just get it here from github, no need for Fdroid.

**Comment by indywidualny** [comment]
Google Play hates me and it's mutual :) Not worth risking my dev account. F-Droid is good as well if not better for such a project.
