### ISSUE TITLE
Activate/Deactivate Menu by Hardware Menu button.

### ISSUE THREAD

**Issue by kamathln** [indywidualny/FaceSlim#37]
Most phones/Android devices have a hardware "menu button". User's of such devices are accustomed to finding menu. It would be nice to follow the same pattern

**Comment by indywidualny** [comment]
http://android-developers.blogspot.com/2012/01/say-goodbye-to-menu-button.html?m=1

Not since 2012 :) 

I follow latest trends so hardware menu button support is not in my plans.

**Comment by kamathln** [comment]
Are you planning to add an action bar then?

**Comment by indywidualny** [comment]
Action bar is in that case a waste of space. Just use swipe gesture to open
the menu. It's a popular gesture and you can even configure the edge of the
screen with the menu.

Traditional, modern menus are made that way too. You can either tap the
action bar to open a menu or just swipe.

I hid the action bar but the gesture works. It's easy, intuitive and
awesome. Way better than tapping somewhere to open the menu :)

wt., 15 wrz 2015, 15:47 Laxminarayan G Kamath A użytkownik <
notifications@github.com> napisał:
