### ISSUE TITLE
clear cache preference should not  logout

### ISSUE THREAD

**Issue by jidanni** [indywidualny/FaceSlim#39]
Why must clear app cache  preference item also log one out? If I clear it via the Android app manager it doesn't log me out thankfully. Can't data and cache be separate?

**Comment by jidanni** [comment]
I never actually dared to test it.

**Comment by indywidualny** [comment]
That option in the preferences is made to clear all the app data directories. You can clear it less aggressively in Android settings just like you said and you shouldn't be logged out. The option in the settings is an ultimate one and it leaves shared preferences only (app preferences). IMHO it's a good option to delete everything, delete even more than you can delete at Android settings. I can exclude logging out but I wanted to clear cookies too. Sometimes it's usefull in example when switching users.

**Comment by jidanni** [comment]
OK but maybe make all the different kinds of clearing all available there in together in the menus too.

**Comment by indywidualny** [comment]
IMHO duplicating system features is not necessary. You can use Applications Manager to clear app's cache or you can just use an ultimate cleanup option inside this app. Adding another cache cleaning makes no sense to me. It never exceeded 20 MB and it's nothing nowadays.

**Comment by jidanni** [comment]
Perhahps on it mention in more detail that is leaves shared preferences only (app preferences). etc, etc. and zaps cookies thus logging one out.
