### ISSUE TITLE
Make it clear on homescreen that notifications should be setup to be usable

### ISSUE THREAD

**Issue by kamathln** [indywidualny/FaceSlim#42]
Just like describing the refresh and menu usage on the welcome screen, also describe that we need to setup notifications. (If I hadn't accidentally come across it in settings, I would have uninstalled FaceSlim, thinking it doesn't provide notifications) 

Also providing a list of features in F-droid description would make it clear to the users.

**Comment by indywidualny** [comment]
Ok. I will :)

sob., 19 wrz 2015, 10:38 Laxminarayan G Kamath A użytkownik <
notifications@github.com> napisał:

**Comment by pecuna** [comment]
And it should say more how to activate them actually.
Which url the app need?
I haven't figured it out yet.  I pasted RSS feed url, the app stays open and the phone is locked and nothing happens more than 5 mins and I know that I have unread messages.
OS: 4.3.1 Cyanogenmod  (Privacy protector is off for the app).
