### ISSUE TITLE
open *.fbcdn.net links in FaceSlim and not external browser

### ISSUE THREAD

**Issue by kamathln** [indywidualny/FaceSlim#43]
Currently when I click on "View Full Size" link of an image, it asks me to open it in an external browser. It would be nice to open it in FaceSlim.

**Comment by indywidualny** [comment]
I will think about it but it was easier to implement it that way. External
browser allows for example to save the image or zoom in/out. I have to
implement something similar and I can allow openening content from this
domain too.

sob., 19 wrz 2015, 10:54 Laxminarayan G Kamath A użytkownik <
notifications@github.com> napisał:

**Comment by kamathln** [comment]
simply add an option to "open current page in external browser" for any page.. will give loads of flexibility, at the same time will be easier for you to implement as well (I guess)

**Comment by indywidualny** [comment]
And that's a perfect solution. Thanks ;)
I will do so with the new release.

**Comment by indywidualny** [comment]
And I forgot about it again. It should be nice to have a possibility to open everything in external browser however I cannot decide where to place this option. Main menu is a little crowded. Long clicks are reserved for sharing links. Any ideas? Maybe a gesture or something...

**Comment by kamathln** [comment]
long clicking should trigger a context menu with options. 1) Share 2) Open in browser 
That way, you can add more options to it later if needed.

**Comment by indywidualny** [comment]
Well. Simple ideas are great ideas. Thanks ;)

pon., 16 lis 2015, 12:16 Laxminarayan G Kamath A użytkownik <
notifications@github.com> napisał:

**Comment by kamathln** [comment]
Welcome :)

**Comment by pejakm** [comment]
Will this get resolved in the upcoming version?

**Comment by indywidualny** [comment]
This is not ready yet. I tried to do it and there was a problem because long clicks are only possible on links. So it cannot be used to open a current page in external browser. I have to figure something out.

**Comment by pejakm** [comment]
Why complicating things? From my (user) perspective:

 - internal FB links (*.fbcdn.*):
* single click opens link internally
* long click opens context menu with options

 - non-FB (external) links:
* single click opens link in external browser
* long click opens context menu with options (I actually don't care about this one because Facebook already has ability to share something already posted)

Is this the same you are trying to accomplish or perhaps I misunderstood? :)

**Comment by indywidualny** [comment]
Yep but it would be nice to have an option to just open the current page (not a link) in external browser too. And if you long click somewhere there is a text selection/copy. I want to keep it unified too. All long clicks should do the same so internal / non-FB links and different actions for them seem not right.

There is also another problem. If someone set Face Slim as the default application for all Facebook links, opening a Facebook link externally will be caught by Face Slim. There are a lot of web browsers and I cannot just assume someone is using Chrome and open Chrome as an external browser. It's made by universal Intent and the system chooses the right app.

I don't want to mess things :D It needs some time to be done right. The easiest things are sometimes the most difficult.

**Comment by pejakm** [comment]
Sorry for been pushy, I very much miss this feature. Could you point out any quick code edit to enable opening Facebook images inside app itself? "Tinfoil for Facebook" app can do this and I've examined its code but couldn't find anything I could use for Face Slim.

**Comment by indywidualny** [comment]
Done.
