### ISSUE TITLE
Notification URL opens in browser 

### ISSUE THREAD

**Issue by edent** [indywidualny/FaceSlim#44]
When I click "get your notifications feed", my browser opens the following URL `https://goo.gl/t3vJ33`

The browser then redirects me to the Facebook login page.

It would be better if the URl was a direct link to `https://www.facebook.com/notifications` and opened in the FaceSlim app. I don't want to log into FB in my browser.

**Comment by indywidualny** [comment]
There are two reasons why it's redirected.

1. Facebook can change this url in the future (rather unlikely) but it's extremely simple to update all the app versions changing the redirection.
2. I didn't wan this specific url to be opened in this app. I found it comfortable to open another window (web browser in that case), look for a link and just switch windows, so I wanted to use an external domain. Moreover that page looked bad when opened by Face Slim - my app has zoom disabled.

Perhaps it's better to open this url through the app. I will think about it.

**Comment by pecuna** [comment]
Yes it will be more efficient to have it from the app directly. As  mentioned in issue 42, url for RSS is not working on all browsers (Opera Mini for example).
Maybe button ** Get Notification feed ** and it directly takes the url and loads it in the app and you are ready with notifications setup. It is simpler this way.

**Comment by indywidualny** [comment]
But everyone has a different one so it's not so simple :)

niedz., 20 wrz 2015, 19:05 Iskren Mihaylov użytkownik <
notifications@github.com> napisał:

**Comment by indywidualny** [comment]
Not an issue anymore - It's gonna be automatic now. Just log in and activate notifications. The service will retrieve this feed automatically during checking. Gonna be published soon.

https://github.com/indywidualny/FaceSlim/issues/78
