### ISSUE TITLE
Redundant loading spinner pictures on page bottoms

### ISSUE THREAD

**Issue by Jadelor** [indywidualny/FaceSlim#48]
Many FB Slim pages have started showing non-animated and redundant loading spinnet icons on the bottom of the page. See: http://i.imgur.com/uLQOVof.jpg

**Comment by indywidualny** [comment]
Oh, that's something strange. A spinner should be only shown while loading additional content. It should not be present when you are on the bottom of the page. It's Facebook dependant because I'm simply framing the mobile site so I cannot change it. I hope they will fix it.
