### ISSUE TITLE
use different logo

### ISSUE THREAD

**Issue by jidanni** [indywidualny/FaceSlim#50]
1.8.1 still uses FB Corp proprietary logo/icon.  Please use a red FS to not confuse with official FB branding.

**Comment by indywidualny** [comment]
Ok. I will create a new one. This week.

**Comment by indywidualny** [comment]
However this logo is my own image and it's different from to official one (shadow, position of f letter). So I will think twice whether I'm gonna change it.

**Comment by jidanni** [comment]
"Don't modify the ‘f’ logo in any way, such as by changing the design or color."
-- https://www.facebookbrand.com/guidelines?asset=2&media=1,2,3
A judge will say you have taken their logo and only slightly modified it.

Wouldn't you think it wiser to steer clear of their 100? 1000? lawyers by using F instead of f, and better yet FS instead of F, and maybe even a non-coincidentally same color?

"What does Facebook do if people misuse its brand assets?
Facebook dedicates substantial resources to the development and protection of its intellectual property. In addition to seeking registration of its trademarks and logos around the world, Facebook enforces its rights against people who misuse its trademarks."
-- https://www.facebookbrand.com/top-questions

"Can I combine Facebook brand assets with new terms or artwork to create my own marks and logos, or modify the color or design to fit with the style of my website or packaging?
You may not modify Facebook brand assets in any way, such as by changing the design or color. The exception is if you are working in print media or product packaging and you’re unable to use the correct color due to technical limitations. In those cases, you can revert to black and white.

You may scale the size of brand assets to suit your needs, as long as they are not the most distinctive or prominent feature on your web page, printed material, or other content."
 -- same URL.

You are turning me into a lawyer for Facebook. All I know is your logo is so very much like the "real" Facebook lite logo that even we people who don't especially like the Facebook company still do think you are very much confusing users. This is not to mention any legal problems.

**Comment by jidanni** [comment]
https://developers.facebook.com/docs/apps/review/branding :
"Don not use or incorporate Facebook's F logo, or any modification or derivative of the F logo, in your icons or logos."

**Comment by indywidualny** [comment]
http://romannurik.github.io/AndroidAssetStudio/icons-launcher.html#foreground.type=text&foreground.space.trim=1&foreground.space.pad=0.25&foreground.text.text=fs&foreground.text.font=Roboto&foreColor=3b5998%2C0&crop=0&backgroundShape=square&backColor=ffffff%2C100&effects=shadow

Well. I like the color, one cannot own the color. It's just a color.
Instead of "f" it can be "fs". Lower case, not all capitals. 

It's not modifying their "f" logo now.
Does anyone like it? :)

**Comment by indywidualny** [comment]
https://github.com/indywidualny/FaceSlim/commit/b31c965ebf510dfc9d739ddbfa65ccc282e8c722

**Comment by juzman** [comment]
Looks good.

**Comment by jidanni** [comment]
OK I filed https://www.facebookbrand.com/request?id=6264 (which you can't see, so don't click on it).
I asked them if the "fs" logo is far enough away from the "f" logo to make them happy.
"Please note that it takes 2-3 weeks for requests to be processed."
So if I ever hear anything back I will let you know.

**Comment by indywidualny** [comment]
Ok. So I will change the logo to "fs" for now.
Imho it's completely different and should be ok.

wt., 27 paź 2015, 13:55 Dan Jacobson użytkownik <notifications@github.com>
napisał:
