### ISSUE TITLE
Ability to share things

### ISSUE THREAD

**Issue by pejakm** [indywidualny/FaceSlim#53]
I would to see ability for FaceSlim to be on the list of apps when I want to share something (text, for start, but sharing images also would be neat thing to have, if possible).

**Comment by indywidualny** [comment]
I'm thinking hard but I don't think I can do it. This app has so many limitations because i'm only framing Facebook mobile website.

I always wanted to use "Sharer" or "The Feed Dialog" but they are deprecated...
https://www.facebook.com/sharer/sharer.php

Now I have no idea how to share things directly throught their mobile website.

**Comment by juzman** [comment]
I have NO programming experience. However simply adding this intent filter to the activity into the manifest wont work?

<intent-filter>
    <action android:name="android.intent.action.SEND" />
    <category android:name="android.intent.category.DEFAULT" />
</intent-filter>

**Comment by indywidualny** [comment]
Sure but it have to be posted on the wall somehow after receiving this intent. I can capture things easily (like you said) but I cannot figure out how to post them on the wall without a deprecated "Sharer".

**Comment by radasbona** [comment]
In Tinfoil for Facebook it is possible to share links via share dialog. I'm no coder, but maybe you find a solution here: https://github.com/velazcod/Tinfoil-Facebook

**Comment by indywidualny** [comment]
Thanks. I will check out out. Tinfoil is open source so I can use a part of its code to achieve it. Great tip.

**Comment by indywidualny** [comment]
Ok. Next week it will be possible to share links. Yay!

**Comment by juzman** [comment]
That sounds awesome.

**Comment by juzman** [comment]
All Facebook needs now is the ability to tag people with @ and this app is
perfect!

**Comment by indywidualny** [comment]
But it's working with the publish button from your profile... Just type the name in the creator and wait a second. Without @ at the beginning, it's not Twitter :) 

A little secret: I will make easy access to this editor thanks to Floating Action Button (>= Lollipop). Next week or something like that. 

It's actually not about this issue so closed for now. Feel free to create another issues :)

**Comment by pejakm** [comment]
I've tested this just now, and it's great. Thank you. However, it's only possible to share links, not text or images. Any chance we might see this, too, in near future?

**Comment by indywidualny** [comment]
I don't think so. I used a piece of code from Tinfoil. It allows to share
links (and extract links from text) only. I'm afraid sharing images will
not be possible through my app.

sob., 14 lis 2015, 13:17 Mladen Pejaković użytkownik <
notifications@github.com> napisał:

**Comment by radasbona** [comment]
Works very well. Thanks
