### ISSUE TITLE
Pinch zoom

### ISSUE THREAD

**Issue by censlin** [indywidualny/FaceSlim#56]
It would be a slightly faster way to view small images than opening them up externally.

**Comment by indywidualny** [comment]
I'm thinking about it but pinch gesture is disabled here - https://m.facebook.com

This app is a simple wrapper. I will think how to achieve it anyway but no promises.

**Comment by juzman** [comment]
Would something like this work @indywidualny 

http://stackoverflow.com/questions/10630373/android-image-view-pinch-zooming

**Comment by censlin** [comment]
Hmm, seems like a different idea, but one I'm still happy with.
Seems like they are only expanding a single image within the page. I had expanding the whole page in mind.
I'm happy with either option, so I'd say go with whichever is easiest.

On that note, Tinfoil For Facebook has the expand whole page option implemented, so it might be worth looking into their code.

On 10 January 2016 07:55:34 SAST, Justyn Smith <notifications@github.com> wrote:
>Would something like this work @indywidualny 
>
>http://stackoverflow.com/questions/10630373/android-image-view-pinch-zooming
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/indywidualny/FaceSlim/issues/56#issuecomment-170316811

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by juzman** [comment]
That would be easiest if tinfoil already have it. :-)

**Comment by indywidualny** [comment]
Done.

**Comment by censlin** [comment]
Thanks

On 16 January 2016 07:16:48 SAST, Krzysztof Grabowski <notifications@github.com> wrote:
>Done.
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/indywidualny/FaceSlim/issues/56#issuecomment-172159111

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
