### ISSUE TITLE
Won't install on f droid

### ISSUE THREAD

**Issue by SethArchambault** [indywidualny/FaceSlim#57]
Clicking install gives the message "not installed"

**Comment by indywidualny** [comment]
Are you updating the app or "clean" installing it? Could you give me some details about the situation?

**Comment by indywidualny** [comment]
Please also notice that if you are using a Github version you need to remove it first to install an F-Droid version due to different signing certificates.

**Comment by indywidualny** [comment]
Ok. Perhaps it's solved. I told the reason and the solution. It's the only possibility for this situation.
