### ISSUE TITLE
Translate to Portuguese

### ISSUE THREAD

**Issue by antun3s** [indywidualny/FaceSlim#61]
I would like to help translate to Portuguese.
Where i van do it?

**Comment by indywidualny** [comment]
Here is the English version -  https://github.com/indywidualny/FaceSlim/blob/master/app/src/main/res/values/strings.xml

Copy its content to a new file located in app/src/main/res/values-pt/strings.xml, remove all the translatable = false strings, do a translation (change string values) and create a pull request. Easy to do :) 

For example values-pl is a Polish translation.

**Comment by antun3s** [comment]
Another question. The Portuguese has some characters like "ç" and "ã," I can put them, or need to put the code "&#8635;"

**Comment by indywidualny** [comment]
You can use all the signs normally. It's UTF-8 :)
Just use your keyboard and type whatever you want.

**Comment by indywidualny** [comment]
Thanks for translation! If you want to change something just create a pull request any time.
