### ISSUE TITLE
Cannot select text 

### ISSUE THREAD

**Issue by xavihernandez** [indywidualny/FaceSlim#62]
It is not possible to select text. Would be good tho.

**Comment by indywidualny** [comment]
Have you tried clicking at the thing you want to select to fully open it and then select it? I suppose long click listener (sharing urls) is capturing the click. Timeline is full of links.

**Comment by xavihernandez** [comment]
Oh ok thank you. When not in Timeline I can select text. :)

**Comment by indywidualny** [comment]
Awesome. I had to do it this way because I wanted ability to share links
too.

sob., 14 lis 2015, 15:14 Eric Mourougandy użytkownik <
notifications@github.com> napisał:
