### ISSUE TITLE
Release 1.9.0 soon, please do final changes

### ISSUE THREAD

**Issue by indywidualny** [indywidualny/FaceSlim#67]
Is anyone supporting latest development (translations, black theme) going to change something for this version? I'm ready to publish a new version, everything seems to work fine. It would be nice to publish it today at night (F-Droid builds new releases around 4-6 a.m.)

If you need more time just tell me. No need to hurry :smiley:

**Comment by pejakm** [comment]
Consider moving translation efforts to Weblate:
https://hosted.weblate.org/

**Comment by indywidualny** [comment]
I will. It looks like a great idea although I actually like getting
translations through pull request. It's extremely convenient for me because
I can apply changes immediately.

I will test this website.

pon., 16 lis 2015, 18:52 Mladen Pejaković użytkownik <
notifications@github.com> napisał:

**Comment by indywidualny** [comment]
http://www.oneskyapp.com/how-it-works/translation-management-system/

IMHO it will be better.

**Comment by pejakm** [comment]
This is not FLOSS. Besides, there are a bunch of other proven translation platforms, like Crowdin and Transifex, none of them so simple, effective and open as Weblate.
