### ISSUE TITLE
1.9.1 often has us staring at the logo waiting for start up

### ISSUE THREAD

**Issue by jidanni** [indywidualny/FaceSlim#69]
Version 1.9.1 often has us staring at the fs logo in the middle of the screen waiting for start up. Previous versions didn't take as long to start.

**Comment by indywidualny** [comment]
A splash screen is shown while a Facebook page is loading for the first time. It disappears after the page is fully loaded. Loading times should be the same although you may feel differently. 

Before,  a timeline was gradually appearing at the screen. Until it was ~95% loaded the app was useless anyway. You could see a progress so it could seem faster but you still couldn't use a timeline. 

I thought it's better to show a 100% loaded page after an app start when the page is ready to use and nothing is missing. A splash screen also looks nice. 

I didn't change anything which could affect loading times anyway.

**Comment by jidanni** [comment]
Couldn't we still read part of it while it was loading?
(Or at least add some progress indicator so we know our phone isn't dead, like official Lite does.)

**Comment by indywidualny** [comment]
The indicator is a nice idea. Ok.

wt., 17 lis 2015, 15:39 Dan Jacobson użytkownik <notifications@github.com>
napisał:

**Comment by jidanni** [comment]
Many users use slower phones / connections.

At least we could read 95% of the screen while it was loading. And then cut it short by pushing the messages or notifications or friends icons.

Now we are stuck looking at the logo until 15, 30, or even 60 second screen blank timeout arrives!

**Comment by indywidualny** [comment]
I'm still experimenting with it. I will probably make it to disappear
quicker. IMHO about 70% should be good.

śr., 18 lis 2015, 21:35 Dan Jacobson użytkownik <notifications@github.com>
napisał:

**Comment by indywidualny** [comment]
I made it faster. When page is ~65% loaded so it's almost complete a splash screen will disappear. An Indicator will not be necessary. It's blazing fast.

**Comment by indywidualny** [comment]
Ok, now it's even less, >= 50% and you can hide a splash screen any time just pressing "back".
