### ISSUE TITLE
Translate 2 additional strings, please

### ISSUE THREAD

**Issue by indywidualny** [indywidualny/FaceSlim#73]
New release (2.0.0) has support for disabling images. There are 2 new strings for this option.

```
<string name="no_images">Disable images &#8635;</string>
<string name="no_images_description">Don\'t load any images. Reduces data usage drastically.</string>
```

I would be gratefull if you could translate those two :)
@antun3s @de-live-gdev @pejakm @panenka @G33KS44n 

Korean translation has more strings missing. It would be awesome to make it complete :) @halcyonest

**Comment by panenka** [comment]
Hello, Czech version has been translated.
Regards, Vaclav Panenka
Dne 22. 11. 2015 13:36 napsal uživatel "Krzysztof Grabowski" <
notifications@github.com>:

**Comment by indywidualny** [comment]
Awesome!

**Comment by antun3s** [comment]
I'll put here because I can not use the right github (im n00b)
sorry.
<string name="no_images">Desativar imagens &#8635;</string>
<string name="no_images_description">Não carregará nenhuma imagem. Reduz drasticamente o uso de dados.</string>

**Comment by de-live-gdev** [comment]
DE coming today or tomorrow.

**Comment by indywidualny** [comment]
Yay!

**Comment by halcyonest** [comment]
Send me some untranslated strings then I'll translate it back quickly :)

**Comment by antun3s** [comment]
Disable images &#8635;
Don\'t load any images. Reduces data usage drastically.

Enviado por TypeMail



Em 26 de nov de 2015 23:25, pelo 23:25, Joseph Kim <notifications@github.com> escrito:

**Comment by indywidualny** [comment]
We are talking about Korean translation so more strings are missing. I'm just checking what's missing and I will let you know :) Thanks in advance.

**Comment by indywidualny** [comment]
@halcyonest Ok, here it is. You may check whether already translated strings are ok - one of them was changed for sure. https://www.dropbox.com/s/vpzlxtcyijn0zfr/translations.csv?dl=0

**Comment by indywidualny** [comment]
Well, there is one more. I'm adding full Marshmallow support and this string is needed for runtime permissions.

``<string name="no_storage_permission">Grant storage permission to use this feature.</string>``

Could you send me this line, please? You can even paste it below, as a comment :)

**Comment by de-live-gdev** [comment]
[de]  Die Speicher-Berechtigung muss erteilt werden, um dieses Feature nutzen zu können.

**Comment by halcyonest** [comment]
<string-array name="drawerPosTitles">
        <item>왼쪽</item>
        <item>오른쪽</item>
    </string-array>

    <string-array name="intervalPrefTitles">
        <item>5분</item>
        <item>15분</item>
        <item>30분</item>
        <item>1시간</item>
        <item>3시간</item>
        <item>6시간</item>
    </string-array>

And [file](https://github.com/indywidualny/FaceSlim/files/53899/translations_ko.txt) is uploaded. Change its file extension to CSV.

**Comment by indywidualny** [comment]
![scrot](https://cloud.githubusercontent.com/assets/9354672/11671686/6aff754a-9e0a-11e5-88d5-b574d24c49cf.png)

Almost everything is translated. Nothing important is missing. Thanks guys! :+1:
