### ISSUE TITLE
Editing Post removes attachment

### ISSUE THREAD

**Issue by juzman** [indywidualny/FaceSlim#79]
I shared a video from YouTube and worked fine. However when I went to the post, tapped the little dropdown and choose "edit post", I can edit the post, but the video isn't attached anymore.

**Comment by indywidualny** [comment]
Well, it's Facebook Mobile related. I'm only framing the website. 

It happened to me too. There is a solution. Don't remove an url from the post when editing or publishing for the first time. Leaving an url in your published post makes sure the attachment will not disappear.

**Comment by juzman** [comment]
Nice to know, thanks!
