### ISSUE TITLE
foreign accents not working on my physical keyboard

### ISSUE THREAD

**Issue by landry314** [indywidualny/FaceSlim#82]
i have a samsung galaxy s relay 4g running CM 11. when i hold down physical keys on my keyboard to bring up accent choices, nothing comes up: it just repeats the character many times, but with my on-screen keyboard it does bring up accent choices.

in firefox on the facebook site, holding down a physical key DOES make foreign accents come up so this is only a problem with faceslim calling the keyboard routine and not with the os in general.

in telegram, handcent and the stock messaging app, the accents work. in firefox, it works. it is only faceslim that does not call the accents up when the keys are held down.

i know this must affect very few people but, hey, it could be a quick fix... :-\

**Comment by indywidualny** [comment]
It may be a WebView problem (embedded Chrome client, actually Chromium). I don't think there is much to do. Does it work in Google Chrome?

**Comment by landry314** [comment]
no, i just checked, same problem in google chrome... sucks...

**Comment by indywidualny** [comment]
I'm sorry to hear that.
