### ISSUE TITLE
pasting text into a blank private message does not allow send until edit

### ISSUE THREAD

**Issue by landry314** [indywidualny/FaceSlim#85]
when i paste text into a blank private message the send button is not available until some edit is made to the text. i have to delete a character and type it back in every time i want to directly copy and paste something into a message.

**Comment by landry314** [comment]
i just checked this in google chrome and there we find the same bug... so it is yet another google chrome problem... you would think google would be more on top of there own browser...

**Comment by indywidualny** [comment]
Yeah, it's annoying. Especially while pasting an url and trying to send it immediately. 

Personally I add a single space after pasting something. This way I can send a pasted text quickly.

**Comment by kamathln** [comment]
Could you inject some javascript to overcome please :)

**Comment by landry314** [comment]
tinfoil for facebook does not have this problem. are they based on chrome as well? you could look at their code.

**Comment by pejakm** [comment]
I'm having this problem on my browsers, too (Lightning Browser, Aurora, Firefox), so this is probably a problem with the facebook site itself.

**Comment by landry314** [comment]
Well, I guess we can chalk this up as more intentional facebook negligence towards their mobile web version.
