### ISSUE TITLE
Suggestion: Mobile basic version of facebook

### ISSUE THREAD

**Issue by bastadur** [indywidualny/FaceSlim#86]
Is it possible to add the basic facebook version mbasic.facebook.com? Tinfoil has it, but I like your app better.

**Comment by indywidualny** [comment]
I would like to do it but I just visited this website and got automatically
redirected to mobile.facebook.com (a normal mobile version).

It seems not working on all devices.

wt., 15 gru 2015, 15:57 bastadur użytkownik <notifications@github.com>
napisał:

**Comment by bastadur** [comment]
It works on my Xperia SP with android 5.1 on it.

Maybe it could be solved by setting an older UA string for that option? It's just a guess, I'm not a developer.

**Comment by indywidualny** [comment]
I can introduce it as an experimental feature. No guarantees, if it works, than great. If it doesn't, no problem.

**Comment by indywidualny** [comment]
Ok, it seems to be working well. Gonna be released after I will add some new features :)

**Comment by bastadur** [comment]
Thanks a lot man!
