### ISSUE TITLE
facebook hidden server

### ISSUE THREAD

**Issue by abate** [indywidualny/FaceSlim#90]
Another small request . I use facebook only thought tor. Can you add to the preference the option to use the facebook hidden service : https://facebookcorewwwi.onion/ ?

thanks again :)

https://blog.torproject.org/blog/facebook-hidden-services-and-https-certs

**Comment by indywidualny** [comment]
Not this year :D It seems to be a duplicate, I will find the original request later.
It's not so easy to do so I need some time but it's gonna be finally introduced (I'm not sure when though).

**Comment by indywidualny** [comment]
#18
