### ISSUE TITLE
Open links in-app with a blank page 

### ISSUE THREAD

**Issue by Optokus69** [indywidualny/FaceSlim#91]
There's a bug since 2.0 that I have on my Samsung S5 running Alliance ROM V9 (Lollipop). 
Every time I want to open an external link, it loads a blank pages (black as I'm running a dark theme) then opens a link in external browser. 
Can it either load in external browser without opening this page or can it load it in-app in a new tab, as it's anyways running on Web View? 
Thanks.

**Comment by indywidualny** [comment]
I will try to do something about it. Thanks for info.

**Comment by juzman** [comment]
Would something like Chromer from the Play Store fix this?

**Comment by indywidualny** [comment]
Loading external sites in-app seems not a good idea (privacy issues). It has to be opened in browser. I'm still not sure about that blank page. I cannot reproduce it.

**Comment by indywidualny** [comment]
Ok. I know what may cause the problem. Do you have "basic mode" enabled? When mbasic page cannot be loaded Facebook gives us a normal one. Those redirections can cause the problem so don't check the option unless it's working.

**Comment by indywidualny** [comment]
Seems to be fixed today.
