### ISSUE TITLE
long press should allow copy link URL

### ISSUE THREAD

**Issue by jidanni** [indywidualny/FaceSlim#93]
In a real browser long pressing links like "3 hours ago" allow one to copy the URL etc. Why can't we do that? Else just jumping to the same article we are reading isn't very useful.

**Comment by indywidualny** [comment]
You can copy all the links too. Just enable long clicks :) 
While sharing there is a system shortcut: "copy to clipboard".

![screenshot_20151225-235803](https://cloud.githubusercontent.com/assets/9354672/12004566/8b97698c-ab63-11e5-8ad1-bb3cc0bfa99b.png)
