### ISSUE TITLE
[Feature request] Add an option to hide sponsored posts / ads

### ISSUE THREAD

**Issue by robrobinbin** [indywidualny/FaceSlim#94]

**Comment by hu475** [comment]
Seconded.

**Comment by robrobinbin** [comment]
I don't know much about android development, but I guess the "dark theme" and "fixed blue bar" options are implemented by injecting CSS into the page. I've looked in the EasyList block list and found these 8 element hiding rules for m.facebook.com

    m.facebook.com###m_newsfeed_stream article[data-ft*="\"ei\":\""]
    m.facebook.com,touch.facebook.com##.aymlCoverFlow
    m.facebook.com,touch.facebook.com##.aymlNewCoverFlow[data-ft*="\"is_sponsored\":\"1\""]
    m.facebook.com,touch.facebook.com##.pyml
    m.facebook.com,touch.facebook.com##.storyStream > ._6t2[data-sigil="marea"] 
    m.facebook.com,touch.facebook.com##.storyStream > .fullwidth._539p 
    m.facebook.com,touch.facebook.com##.storyStream > article[id^="u_"]._676 
    m.facebook.com,touch.facebook.com##.storyStream > article[id^="u_"].storyAggregation

If I'm not mistaken this corresponds to injecting the following CSS into the m.facebook.com webpage

    #m_newsfeed_stream article[data-ft*="\"ei\":\""],
    .aymlCoverFlow,
    .aymlNewCoverFlow[data-ft*="\"is_sponsored\":\"1\""],
    .pyml,
    .storyStream > ._6t2[data-sigil="marea"],
    .storyStream > .fullwidth._539p,
    .storyStream > article[id^="u_"]._676,
    .storyStream > article[id^="u_"].storyAggregation {
        display: none !important; 
       /*I don't know whether the !important is needed*/
    }

I've tested this using Stylish on the desktop and all the ads on m.facebook.com were gone (tbh only the fist selector seemed to do something during my short test)

I think implementing this feature can be quite easy, the only possible drawback is that these rules need to be kept up to date if facebook updates its site.

**Comment by hu475** [comment]
Cheers. Will try these with AdAway and update this thread for reference (or for a workaround if not possible to block the sponsored posts in Face Slim).

**Comment by robrobinbin** [comment]
I don't think AdAway can do this, I think AdAway only blocks domains (eg. Imagine facebook stores all it's ads on something like FacebookAdServer.com and Facebook.com loads ads from there. AdAway can block all requests to FacebookAdServer system wide, so you wont see ads on facebook) but sponsored posts are directly embedded in the web page (they come from the same domain than normal facebook posts), thus these ads can't be stopped system wide (without blocking facebook completely), they need to be hidden by the application themselves (using something like CSS). 
I could be wrong about this, and if it does work with AdAway somehow I'll be very happy!

**Comment by indywidualny** [comment]
It can be done for sure. I can modify css. Just give me some time. Busy
days now.

pt., 1.01.2016, 10:51 robrobinbin użytkownik <notifications@github.com>
napisał:

**Comment by indywidualny** [comment]
I'm afraid it only works for the first section. Dynamically loaded items cannot be styled. But... most of ads are at the top of the page. Am I right?

I hope it works. Didn't tested yet.

**Comment by indywidualny** [comment]
Is everything ok? Can I close it now? 
My news feed has actually no ads so I cannot see the difference.

**Comment by robrobinbin** [comment]
I installed FaceSlim/app/app-release.apk yesterday and enable the option, but I'm still getting ads :(

![screenshot_20160112-204116](https://cloud.githubusercontent.com/assets/8597693/12274923/834d64da-b96d-11e5-8084-bb067552779e.png)
![screenshot_20160112-204236](https://cloud.githubusercontent.com/assets/8597693/12274921/834ad314-b96d-11e5-9696-f6ae29733d0b.png)
![screenshot_20160112-204134](https://cloud.githubusercontent.com/assets/8597693/12274922/834d4da6-b96d-11e5-8249-4d1c7b43ab66.png)

**Comment by indywidualny** [comment]
Not good :(

I think ads cannot be hidden for a dynamically loaded content. So in fact it only disables some of the sponsored posts. Only ads at the top of the page should be gone.

Are there any ads for a statically loaded content (e.g. top of the page, after refresh)?

**Comment by robrobinbin** [comment]
I had to scroll down quite a bit to find an ad, but I opened m.facebook.com in a normal (non ad blocked) browser and I had to scroll down just as far (there weren't simple any sponsored posts earlier). I think yesterday I had an ad higher up, but I'm not sure. Why is it that dynamically loaded content can't be hidden? When you enable night mode dynamically loaded comments are also styled. Sadly I don't know much about android development and I don't have the right IDE's installed. When you change `display: non !important` to `background-color: red !important` do you get any ads with a red background? Are only the ads at the top red?

**Comment by indywidualny** [comment]
I will test it (red backgrounds).
A good point about a dynamically loaded content - it should work too.

wt., 12.01.2016, 21:27 robrobinbin użytkownik <notifications@github.com>
napisał:

**Comment by sedrubal** [comment]
Can you also try to hide "Install fb messenger!!!1eleven" banners? :D

**Comment by indywidualny** [comment]
Sure. I will hide it by default today.

**Comment by juk47ht** [comment]
Can we close this? Thanks to your work, it's been a month I haven't see any ads on Face Slim.

**Comment by indywidualny** [comment]
Yeah. I wanted to make sure it's working. Great! :)
