### ISSUE TITLE
Prevent image loading in cellular data only?

### ISSUE THREAD

**Issue by kr428** [indywidualny/FaceSlim#95]
Folks,

the possibility to not load images is really helpful. Could this by any chance be extended to only load pictures in demand and only do so while in 3G or cellular data? Loading images immediately is pretty nice in WiFi. ;)
Thanks!
Kristian

**Comment by indywidualny** [comment]
This option works strange and cannot be disabled so easily. That's why changing it needs an app restart. I'm not sure whether it's possible to change it dynamically regarding a connection type. Well, it's possible for sure but I remember it wasn't so reliable. I will think about it though.
