### ISSUE TITLE
Black Theme - problem with 2FA code

### ISSUE THREAD

**Issue by edent** [indywidualny/FaceSlim#96]
Minor issue.  

* User has 2FA switched on at Facebook.
* User has  "black theme" set in FaceSlim.
* User logs in to FaceSlim for the first time.
* Facebook sends a one time code via SMS.
* User tries to type in the code - they see this screen which has black text on a dark grey background.

![screenshot_20160102-164738](https://cloud.githubusercontent.com/assets/837136/12075213/fa6b46c2-b170-11e5-8731-dec19f32693c.png)

* Ideally needs a CSS rule to either make the entered number or the input field white.

Nexus 6, running 6.0.1 (CM13).  FaceSlim v2.1.0 from F-Droid.

**Comment by indywidualny** [comment]
Yep. One extra CSS rule is needed. It can be hard to locate this form because I'm not using this security feature. It may be fixed in the future but it's not really that important to be hurry :) 

@drbeat what do you think?

**Comment by drbeat** [comment]
shouldnt be a problem but sadly i deactivated my fb account :smile:

**Comment by juzman** [comment]
I believe the CSS for this is: textarea, .inputtext, .inputpassword { color: #fff; } but *only* for black theme, otherwise the text will be white on normal theme.
