### ISSUE TITLE
At messages keyboard hides text field

### ISSUE THREAD

**Issue by bcsopi** [indywidualny/FaceSlim#98]
My keyboard hides the text input field on the bottom making text entry quite annoying :D
The black selector thumb can be seen on the screenshot through the keyboard... 
![tmp_4125-screenshot_2016-01-04-10-29-01-92783918](https://cloud.githubusercontent.com/assets/11555574/12086932/b018c734-b2ce-11e5-9f00-60cd719bb4c3.jpg)

**Comment by indywidualny** [comment]
I have no idea for now. 
Please use "app -> info -> email author" to send me some details about your device. I'm interested in the automatically added debug signature only. I have to Google the issue :)
